### ISSUE TITLE
Change the method to access the debug mode (hidden menu)

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1001]
Instead of going to about page and use a remote control or keyboard to enable the debug mode, make it possible by tapping 7 times on the version number under the logo (bottom right of the screen )

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 please add this feature
hide the debug menu when i tap once on version number

**Comment by ghassenbenzahra123** [comment]
> @ghassenbenzahra123 please add this feature hide the debug menu when i tap once on version number

Sure i'm on it @ibrahim-zehhaf-mawaqit
