### ISSUE TITLE
Iqama time message screen

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1029]
![IMG_1071](https://github.com/mawaqit/android-tv-app/assets/158289808/f99c33cc-b07c-47a6-bb12-d827baf86e5f)

It was good if the "Highlight the iqama on the screen" was enable, the iqama time would appear on the message screen instead of the azan.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@mawaqit/android-tv if the option iqamaMoreImportant from /config api so add iqama in all the secondary screens (annoucements, hadith...etc)
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/e5cf52d9-e3dc-4cb0-abd1-47e5d406e44f)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
![IMG_3003](https://github.com/mawaqit/android-tv-app/assets/97339607/4a5c0bcc-f501-4b61-8a85-0aedea2cf811)

iqama should appear only if highlight iqama is enabled
