### ISSUE TITLE
Flash message end date

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1036]
If you want the message to end today you have to set tomorrow's date.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@mawaqit/android-tv the endDate is included 
For example if, the endDate is 2024-03-25 so the flash message must be displayed on 25 and hidden on 26
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/c3fa7efb-e24e-4844-aeb4-b8ec9c114b1e)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 i scheduled a message to start on April first and finish on the same date but it doesn't appear today 
It should start at 0am and finish at 11:59:59pm on the same date

id 1 
![IMG_2789](https://github.com/mawaqit/android-tv-app/assets/97339607/3e5101e9-02ec-47c6-bf3c-c4c72c1d5151)
