### ISSUE TITLE
announcements start and end date

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1037]
It would be nice if the annoucements had the option of a start and end date like "flash message".

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The dates exist but it's not handled on the frontend 
@mawaqit/android-tv please take into account the start and end date if exist to display the announcement 
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/02d7aa20-61f3-4752-9cab-3b1c545d4c1b)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
There are some issues, please check discord
