### ISSUE TITLE
Undesired Timetable change

### ISSUE THREAD

**Issue by galere** [mawaqit/android-tv-app#1039]
**Describe the bug**
User sets their timetable to change Iqama time starting from Monday every week for the 5 daily prayers and this will continue for the rest of the week till the next Monday.

The issue observed is for Sunday Isha prayer, As soon as Adhan time is due, the time of Iqamah changes immediately to show the next week's Isha Iqama which misleads people who want to observe Jamat at the mosque.

The problem is that the countdown flashing iqamah sign doesn't come up when it is iqamah time. It only works for Maghrib salat

**Comment by ibrahim-zehhaf-mawaqit** [comment]
thanks brother
This is issue is related to this one https://github.com/mawaqit/android-tv-app/issues/909
Will fix it insh'Allah
