### ISSUE TITLE
BIG MISTAKE TRANSLATIOn (INDONESIAN-MALAY) 

### ISSUE THREAD

**Issue by YmaneMawaqit** [mawaqit/android-tv-app#1050]
> <div class="intercom-container"><img src="https://downloads.intercomcdn.com/i/o/974853904/cf513f89fcd2a608037418bb/IMG_20240227_052054.jpg"></div>

**Link:** [Conversation with donahs78@gmail.com](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900167122)

**Customer:** [donahs78@gmail.com](https://app.intercom.com/a/apps/piphhhai/users/65915333ec4174fe7db059e6/all-conversations)
**Customer ID:** 32389
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900167122) when this issue is closed.

**Comment by YmaneMawaqit** [comment]
![trans mistake ](https://github.com/mawaqit/android-tv-app/assets/139760274/1d392ae9-03f2-49bf-8945-01fea0849793)
<img width="1225" alt="Capture d’écran 2024-03-04 à 10 53 29" src="https://github.com/mawaqit/android-tv-app/assets/139760274/0e9f08dc-f212-4a6a-8084-c22fc7ab115e">

CORRECT TEXT: 
Dari sahabat Anas bin Malik (رضي الله عنه), Rasulullah ﷺ bersabda,
إِنَّ الدُّعَاءَ لَا يُرَدُّ بَيْنَ الْأَذَانِ وَالْإِقَامَةِ، فَادْعُوا
“Sesungguhnya doa yang tidak tertolak adalah doa (yang dipanjatkan) di antara adzan dan iqamah, maka berdoalah (di waktu itu).” (HR. Ahmad no. 12584)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Will be available in the next release
