### ISSUE TITLE
The digital keyboard is not working on some devices like chrome cast 4

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1070]
https://github.com/mawaqit/android-tv-app/assets/97339607/933f0f43-2c8d-4ca9-9969-1972472bfd75

**Comment by knarkzel** [comment]
Having same issue on Android TV.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> Having same issue on Android TV.

Which model ?

**Comment by MShoebPT** [comment]
same issue in Mi Tv Stick Xiaomi.
