### ISSUE TITLE
Blank screen jumuaa stream in offline mode

### ISSUE THREAD

**Issue by ghassenbenzahra123** [mawaqit/android-tv-app#1077]
- Blank screen at jumua time in offline mode Home Id 3.

![IMG_2755](https://github.com/mawaqit/android-tv-app/assets/35707318/739bb215-75dc-4a1e-8835-0a6aa08eea11)

- When offline the jumua stream can't be played so it should fallback on hadith reminder if enabled or black  screen if enabled

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I tested with the app online and it showed dikr instead of the youtube live
id 3

**Comment by ghassenbenzahra123** [comment]
Fallback behavior works as expected. The issue is in the JumuaStream logic.
