### ISSUE TITLE
About changing the Bip sound in Adhan and Iqama

### ISSUE THREAD

**Issue by FirasTelmoudi** [mawaqit/android-tv-app#1090]
السلام عليكم ورحمة الله وبركاته
I noticed that you have Duaa Iftar and Adhans mp3 files in /assets/voices
I was wondering if i could select them instead of the annoying Bip sound
Thank you

**Comment by ibrahim-zehhaf-mawaqit** [comment]
already fixed, please update the app

**Comment by FirasTelmoudi** [comment]
After the Adhan there's no sound telling the Duaa
Only the Duaa displayed on the screen
