### ISSUE TITLE
The time remaining for iqama after the call for prayer

### ISSUE THREAD

**Issue by ikerfah** [mawaqit/android-tv-app#1091]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The app currently only shows the time of the prayer and the waiting time between the prayer and iqama, Id like to have a countdown timer to tell how many minutes lefts for the iqama

EDIT: it seems like you have it on the tv app, is it possible to have it on the IOS app as well?

![image](https://github.com/mawaqit/android-tv-app/assets/20401578/e3eb7acf-6ac2-4c70-b271-fe0d1cd57a09)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salam alaykum
An issue already exist on the mobile app project

**Comment by ikerfah** [comment]
@ibrahim-zehhaf-mawaqit link please?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The mobile repository is private
