### ISSUE TITLE
Temperature unit changes but the actual value remains in degrees Celsius.

### ISSUE THREAD

**Issue by BanglaQuran** [mawaqit/android-tv-app#1092]
**Describe the bug**
Setting the temperature unit to F does not change the value of the temperature. i.e. Currently it's 30C in Doha, Qatar. When set to F, it should display 86F. Instead, the TV displays 30F, which is wrong. When changed to C in the web backend, it shows 30C (which is accurate). I tried it on my raspberry Pi Mawaqit as well and the behavior is the same.
Note: When I visit the URL from "Widget for your website" link, it displays the correct temperature, 87F (displays 30C when set to Celsius). One degree offset is acceptable due to rounding up/down.

**To Reproduce**
1. Go to Mawaqit backend management website
2. Click on 'Actions' then 'Configure'
3. Click on 'Regional settings'
4. Change Temperature unit from C to F
5. Save

**Expected behavior**
On TV it should change the degrees C to degrees F. Also, the actual value should reflect the change as well.

**Screenshots**
Can be added if needed.

**Android TV/Box (please complete the following information):**
 - Device: MawaqitBox (square shaped)
 - OS: Android 12
 - Version 1.9.3
 - Build 307

**Additional context**
'Font color' of the temperature value and unit remains the same, which is accurate. i.e. 30C shows orange color. When switched to F, it shows 30F in orange color. When temperature raises to 32C, both 32C and 32F is red in color.

**Comment by YassinNouh21** [comment]
backend isn't update the value after setting Celius

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Will create an issue on the backend
