### ISSUE TITLE
Replace sabah time with shuruq on the subscreen (Turkish UI)

### ISSUE THREAD

**Issue by ghassenbenzahra123** [mawaqit/android-tv-app#1122]
- Make the same times appear on both screens. We must replace sabahtime with shuruq on the subscreens.

![Screenshot_20240429_111411_MAWAQIT](https://github.com/mawaqit/android-tv-app/assets/35707318/071c7397-de46-487f-bf4c-6554d10345af)

![Screenshot_20240429_111356_MAWAQIT](https://github.com/mawaqit/android-tv-app/assets/35707318/aca05923-9a89-400e-b016-d891b1b4b14e)

**Comment by Salahaldeen-altous** [comment]
@ghassenbenzahra123 @YassinNouh21 can you please fix this? or it is already fixed?

**Comment by Salahaldeen-altous** [comment]
Tested, seems to be fixed.
Thanks a lot![Screenshot_20240711_211813_MAWAQIT.jpg](https://github.com/user-attachments/assets/4988f4e4-3426-4c8e-826f-c88cfbc9e1ed)

![Screenshot_20240711_211825_MAWAQIT.jpg](https://github.com/user-attachments/assets/3c1f4b46-a786-4f16-bdb5-87001b1c9a08)
