### ISSUE TITLE
add a calculation method 

### ISSUE THREAD

**Issue by YmaneMawaqit** [mawaqit/android-tv-app#1146]
> <div dir="ltr">
<div>Salam alaykoum, <br>
</div>
<div><br></div>
<div>Nous étudions actuellement la possibilité de passer à la méthodologie de calcul des horaires de prière du Moonsighting Committee worldwide (<a href="https://www.moonsighting.com/mcw.html" target="_blank" rel="nofollow">https://www.moonsighting.com/mcw.html</a>).</div>
<div><br></div>
<div>Pourriez-vous ajouter cette option sur mawaqit ?</div>
<div><br></div>Pour une implémentation web respectant les standards javscript, je vous joins le liens d'un répo Github qui contient le code d'un module qui vous faciliterait la modification afin de limiter ce décalage au maximum : <a href="https://github.com/batoulapps/adhan-js" target="_blank" rel="nofollow">https://github.com/batoulapps/adhan-js</a><br><br>Si vous avez la moindre question complémentaire à notre demande, n'hésitez pas à joindre directement notre expert technique sur la question de la configuration à cette adresse : <a href="mailto:contact@coderflight.com" target

**Link:** [Conversation with communication@grandemosqueedeparis.fr](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900169375)

**Customer:** [communication@grandemosqueedeparis.fr](https://app.intercom.com/a/apps/piphhhai/users/6405d02a072a742d5c857a2f/all-conversations)
**Customer ID:** 15877
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900169375) when this issue is closed.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
backend issue
