### ISSUE TITLE
mistake in german translation 

### ISSUE THREAD

**Issue by YmaneMawaqit** [mawaqit/android-tv-app#1150]
> As salam aleikum. I have a little correction for the german translation. The word "nach" is here not correct, this means after. The correct word should be "in". In the legacy mode the correct word "in" is displayed.

Best regards<br>Mohamed

**Link:** [Conversation with mohamed-m@hotmail.de](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900169557)

**Customer:** [mohamed-m@hotmail.de](https://app.intercom.com/a/apps/piphhhai/users/6632a897c04a7873d6e0669b/all-conversations)
**Customer ID:** 41018
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900169557) when this issue is closed.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
After is correct as well
Ishaa After 01:00
