### ISSUE TITLE
NO Main screen Announcements

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1151]
If we choose
NO Main screen
(Your message will be displayed on the main mawaqit screen at mosque)

The announcements also does not appear on the
Secondary screen
(For a secondary prayer room (women room or an other floor for example), this screen will show jumua live-streaming)

Choosing this option (to NO) it should not appear on the main screen but on the secondary screen yes.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
This option is for showing the announcement or not on the TV at mosque, there is no link with main mode or secondary mode
