### ISSUE TITLE
Azan / iqamah time cover images in announcement

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1152]
First of all, I want to thank you for this change. It will be very useful for those who give more importance to iqamah.

I'm going to ask you to find a way to auto adjust images 1920x1080 px (png / jpg) so that the azan / iqamah time do not cover the images.

So far I have a template and adjust the image content manually.
But with this update and other future improvements, always creating a template and adjusting the content manually isn't very useful.

![IMG_1869](https://github.com/mawaqit/android-tv-app/assets/158289808/b4c1199c-1fe4-4ea3-b3ac-c178e391510d)
![1ae082b1-5706-4b7f-b92a-adb6dc34d726](https://github.com/mawaqit/android-tv-app/assets/158289808/2ccf03eb-968a-4dc0-8aae-ff49b9c6d40d)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
We are thinking about a solution insh'Allah

**Comment by ibrahim-zehhaf-mawaqit** [comment]
We will hide prayer times in the bottmm when the message is a picture
