### ISSUE TITLE
Jumuah hadit

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1166]
At juma time, instead of appearing the hadit, a white screen appears.

android box.
![IMG_1968](https://github.com/mawaqit/android-tv-app/assets/158289808/6270b84e-5ca7-48d5-88df-c18704f94190)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 I put this blocking issue in the kiosk mode milestone, can you fix asap please

Mosque ID 683, I can't reproduce it with other mosques
