### ISSUE TITLE
pas de athen lord de salet aser

### ISSUE THREAD

**Issue by g360230** [mawaqit/android-tv-app#1185]
**Describe the bug**
lord de salet aser on ne voit
- ni la mention de adhen
- ni le conteur
- ni ikama
ça passe directement a salet makhreb

**To Reproduce**
1. Avec la configuration de ce mosquée (id: 25969) --> ikamet salet dhoher avent 15 mins de celle de aser
2. Commencez le test lord du conteur pour salet dhoher
3. attendre la fin de salet dhoher
4. une fois que temps de adhen asser arrive 
5. ça passe dirctement vers maghreb sans (adhen, conteur et ikama de aser)

**Expected behavior**
avoir adhen, conteur et ikama de aser

**Screenshots**
https://github.com/mawaqit/android-tv-app/assets/7000968/7fa3af78-3523-4b10-9e42-196dccc84fe2

**Android TV/Box (please complete the following information):**
 - Device: MawaqitBox X96Q
 - OS:  Android 10
 - Version : 1.10.1
- Build : 340

**Additional context**
RAS

**Comment by g360230** [comment]
https://github.com/mawaqit/android-tv-app/assets/7000968/7fa3af78-3523-4b10-9e42-196dccc84fe2

**Comment by g360230** [comment]
Salem 3lykom wara7matou allahi wabarakatoh 

Est ce que vous avez une estimation pour fixer ce bug ?
Les responsables du mosquées demandent des nouvelles 

prière de nous donner une estimation 

baraka allahou fikom

**Comment by g360230** [comment]
Salmon 3lykom wara7matou allahi wabarakatoh 
Si on réduit le temps d’attente entre adhan et ikama de salât dhohr a 5 min le problème n’est plus reprodui 
Le problème est systematic à partir de 10 minutes d’attente 

je suis dispo pour tout besoin/ complément d’info 

baraka allahou fikom

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Can you check in the last version v1.12

**Comment by g360230** [comment]
Salmon 3lykom wara7matou allahi wabarakatoh

sur la version 12 sa passe directement vers Aser plus de salet dhoher

![Screenshot_20240816-154820](https://github.com/user-attachments/assets/b658f456-9218-41c2-a85f-9214108e0c52)

**Comment by g360230** [comment]
Salemou 3alaykom wara7matou allah

désolé je n’ai pas fait attention pour le vendredi 

Sinon je viens de refaire le test avec la version 13
Le problème est persistant 

### juste pour rappel les precondition pour reproduire le problème :
1- ikama dhohr = **15 min avant aser** 
2- durée de salet Dhohr = **10 min (écran noir)**
3- lancez le test avant 20 minutes de aster (pour voir le compte à rebours du dhohr)

### Résultat : 

1- compte a rebours dhohr ——> ok
2- message ikama dhohr ——> ok
3- écran noir dhohr ——> ok
4- adhkar après salet dhohr ——> ok
5- temps restant pour aser ——> ok

6- **adhen aser ——> nok**
