### ISSUE TITLE
white screen during Jum3a

### ISSUE THREAD

**Issue by YmaneMawaqit** [mawaqit/android-tv-app#1187]
> <div dir="auto">السلام عليكم<div dir="auto">رقم المسجد : 16677</div>
<div dir="auto">الجهاز الذي استعمله تلفزيون ٤٣ انتش مثبت بداخله android tv</div>
<div dir="auto">والتفاصيل الاخرى مرققه بلصور.</div>
<div dir="auto">واخرى شي ثبت البرنامج mawaqit for tv على جهاز تلفوني .. samaung z fold 5</div>
<div dir="auto">نفش المشكله حبيت اعرف اذاالمشكله بلتفزيون وكذلك المشكله بلتفون. ونفس رقم النسخه.</div>
<div dir="auto"><br></div>
</div><br><div>
<div dir="ltr">בתאריך יום ג׳, 11 ביוני 2024, 13:12, מאת Ymane de MAWAQIT ‏&lt;<a href="mailto:contact@mawaqit.net" rel="nofollow" target="_blank">contact@mawaqit.net</a>&gt;:<br>
</div>
<blockquote style="margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex">
<u></u> <div dir="ltr"> <div style="color:transparent;font-size:0px;border:0;width:1px;margin:0px;padding:0px;border-width:0px!important;display:none!important;line-height:0px!important"></div> <table cellspacing="0" border="0" cellpadding="0" align="center" style="font-family:Helvetica,A

**Link:** [Conversation with khalid sarsour](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900170243)

**Customer:** [khalid sarsour](https://app.intercom.com/a/apps/piphhhai/users/64836c29222972fd63216874/all-conversations)
**Customer ID:** 25075
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900170243) when this issue is closed.

**Comment by YmaneMawaqit** [comment]
<img width="1255" alt="Capture d’écran 2024-06-21 à 13 20 50" src="https://github.com/mawaqit/android-tv-app/assets/139760274/9761ed2a-53d1-43c9-b8d2-e378f06be459">

ID mosque 16677

**Comment by ghassenbenzahra123** [comment]
Fixed by #1183
