### ISSUE TITLE
"Adhan" n'apparaît pas à l'écran 

### ISSUE THREAD

**Issue by YmaneMawaqit** [mawaqit/android-tv-app#1190]
> Salam Soeur Ymane,<br>J'ai trouvé quelqu'un sur place qui a fait la mise à jour de l'application Mawaqit sur la Mawaqit box. On a installé la dernière version à partir de ce fichier: MAWAQIT-For-TV-v1.10.1-340.apk.<br>Malheureusement le problème n'est toujours pas résolu. Au moment où l'application doit afficher al Athan, elle passe à l'affichage du temps qui reste pour la prochaine salat.<br>Je vous envoie une vidéo qui montre bien le problème.<br>J'espère que ça va permettre à l'équipe Mawaqit d'identifier le problème et de le résoudre dans les meilleurs dalais.

Baraka laho fik.<br>Rachid Moussaoui

**Link:** [Conversation with Rachid Moussaoui](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900168989)

**Customer:** [Rachid Moussaoui](https://app.intercom.com/a/apps/piphhhai/users/65e04f90fefb687a27ec956d/all-conversations)
**Customer ID:** 35600
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900168989) when this issue is closed.

**Comment by YmaneMawaqit** [comment]
https://github.com/mawaqit/android-tv-app/assets/139760274/7304a638-e65c-45a7-a258-0c46f955bcb2

**Comment by ghassenbenzahra123** [comment]
Duplicate of #1185
