### ISSUE TITLE
Code source de l'appli mobile

### ISSUE THREAD

**Issue by mickbot-92** [mawaqit/android-tv-app#1224]
Bonjour 👋
Je voudrais savoir où je pourrais trouver le code source de l'appli mobile.
Merci !
@mickbot-92
P.-S. : faut-il rédiger en anglais ?

**Comment by YassinNouh21** [comment]
> Bonjour 👋 Je voudrais savoir où je pourrais trouver le code source de l'appli mobile. Merci ! @mickbot-92 P.-S. : faut-il rédiger en anglais ?

it is private
