### ISSUE TITLE
Application Auto-Starts After Update on ONVO TV

### ISSUE THREAD

**Issue by YassinNouh21** [mawaqit/android-tv-app#1251]
**Description**:
After updating the `مواقيت` application on ONVO TV, the app auto-starts. This behavior is not desired by regular TV users who prefer to download the application without it launching automatically.

**Steps to Reproduce**:
1. Update the `مواقيت` application on an ONVO TV.
2. Observe that the application starts automatically post-update.

**Expected Behavior**:
The application should not auto-start after an update unless explicitly configured to do so.

**Observed Behavior**:
The application automatically starts after the update on ONVO TV.

**Platform**:
- ONVO TV

**Request for Assistance**:
Could you investigate why this auto-start behavior occurs specifically on ONVO TV and provide a solution to prevent it?

**Media Evidence**:

![image](https://github.com/user-attachments/assets/02e3470b-6862-474d-82b0-312357b23e0a)

![image](https://github.com/user-attachments/assets/0ba2b554-9d24-4119-b57b-e04756f6f173)

![image](https://github.com/user-attachments/assets/565eea5d-0d6c-4dc6-bc70-fb004cd869f9)

**Comment by Salahaldeen-altous** [comment]
I have tried to collect the log with adb

`altoussa@altoussa-XPS-15-9510:~$ adb logcat | grep com.mawaqit.androidtv
08-07 23:27:31.128   621   719 D SystemServerTimingAsync: InitThreadPoolExec:Update app-ops uidState in case package com.mawaqit.androidtv changed
08-07 23:27:31.128   621   719 V SystemServerTimingAsync: InitThreadPoolExec:Update app-ops uidState in case package com.mawaqit.androidtv changed took to complete: 1ms
08-07 23:27:32.187   621   621 V StorageManagerService: Package com.mawaqit.androidtv does not have legacy storage
08-07 23:27:48.170   621   649 I ActivityManager: Start proc 2150:com.mawaqit.androidtv/u0a77 for broadcast {com.mawaqit.androidtv/com.mawaqit.androidtv.BootReceiver}
08-07 23:27:49.291   621   887 I ActivityTaskManager: START u0 {flg=0x10400000 cmp=com.mawaqit.androidtv/.MainActivity} from uid 10077
08-07 23:27:49.295   621   887 W ActivityTaskManager: Background activity start [callingPackage: com.mawaqit.androidtv; callingUid: 10077; appSwitchState: 2; isCallingUidForeground: false; callingUidHasAnyVisibleWindow: false; callingUidProcState: RECEIVER; isCallingUidPersistentSystemProcess: false; realCallingUid: 10077; isRealCallingUidForeground: false; realCallingUidHasAnyVisibleWindow: false; realCallingUidProcState: RECEIVER; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; allowBackgroundActivityStart: false; intent: Intent { flg=0x10400000 cmp=com.mawaqit.androidtv/.MainActivity }; callerApp: ProcessRecord{f0998b1 2150:com.mawaqit.androidtv/u0a77}; inVisibleTask: false]
08-07 23:27:49.450   621   887 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.mawaqit.androidtv  nextpackageName =com.mawaqit.androidtv
08-07 23:27:49.482   621  1727 D CoreBackPreview: Window{1e14b44 u0 Splash Screen com.mawaqit.androidtv}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@992dd62, mPriority=0}
08-07 23:27:49.512   621   887 I ActivityManager: Killing 2150:com.mawaqit.androidtv/u0a77 (adj 905): lowram app for empty# 1
08-07 23:27:49.561   621  1043 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.cvte.tv.launcher.space  nextpackageName =com.mawaqit.androidtv
08-07 23:27:49.857   621   649 I ActivityManager: Start proc 2314:com.mawaqit.androidtv/u0a77 for top-activity {com.mawaqit.androidtv/com.mawaqit.androidtv.MainActivity}
08-07 23:27:51.341   621  1049 D CoreBackPreview: Window{c329d73 u0 com.mawaqit.androidtv/com.mawaqit.androidtv.MainActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@1bd8a9, mPriority=0}
08-07 23:27:51.827   621   817 D CoreBackPreview: Window{1e14b44 u0 Splash Screen com.mawaqit.androidtv EXITING}: Setting back callback null
08-07 23:27:54.448   621  1049 W JobScheduler: Job didn't exist in JobStore: 1e510e4 #u0a77/1423508248 com.mawaqit.androidtv/com.google.android.gms.measurement.AppMeasurementJobService
08-07 23:34:31.007   621  4132 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.mawaqit.androidtv  nextpackageName =com.android.systemui
08-07 23:42:42.707   621   887 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.android.systemui  nextpackageName =com.mawaqit.androidtv
08-07 23:42:42.764   621   887 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.android.systemui  nextpackageName =com.mawaqit.androidtv
08-07 23:42:42.955   621  2286 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.mawaqit.androidtv  nextpackageName =com.android.systemui
08-07 23:42:47.120   621  2286 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.android.systemui  nextpackageName =com.mawaqit.androidtv
08-07 23:42:47.176   621  2286 D ActivityTaskManager: resumeTopActivityInnerLocked prePackageName =com.android.systemui  nextpackageName =com.mawaqit.androidtv
`
`

**Comment by Salahaldeen-altous** [comment]
This behavior have been seen even with normal package update without the launcher being installed.
