### ISSUE TITLE
The freezing of screen in Iran Mosque ID 26564

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1263]
Salam Alaikum our brother Ihsan from Iran install mawaqit as a first mosque there but before 2 days he send this problem one the TV

" Mawaqit usually hangs after the morning prayer and remains fixed on the screen and yesterday, during the evening prayer, the TV image was fixed and did not move, and the temporary program was stopped
And he send me that " Today, to solve the problem, I reset the Android box and reinstalled the applications, After installation, I allowed the application to access the location and memory, The application was launched, but on the top of the screen, despite the Internet, it says not connected
What is this problem and how can it be solved??? "

for more details I added 2 video to explain the problem if we can solve it as soon as possible it will be great

https://github.com/user-attachments/assets/310a8224-f8fc-450a-97a2-77fcfb9462a0

https://github.com/user-attachments/assets/78aa2be2-5c60-4a03-a2a9-169244d0d22c

 thank you

**Comment by MoathALATTAR** [comment]
Selam 
Torday I got a new note from Ihsan 
" Today, after the morning prayer, the mosque screen was checked again
Also, like last night, it did not connect to the Internet and the offline sign was displayed in the software, while the Android Box Internet was active
And to activate the last option in the display settings, it showed the following image "

![Uploading WhatsApp Image 2024-08-10 at 05.19.17_851b141f.jpg…]()

**Comment by ghassenbenzahra123** [comment]
> Salam Alaikum our brother Ihsan from Iran install mawaqit as a first mosque there but before 2 days he send this problem one the TV
> 
> " Mawaqit usually hangs after the morning prayer and remains fixed on the screen and yesterday, during the evening prayer, the TV image was fixed and did not move, and the temporary program was stopped And he send me that " Today, to solve the problem, I reset the Android box and reinstalled the applications, After installation, I allowed the application to access the location and memory, The application was launched, but on the top of the screen, despite the Internet, it says not connected What is this problem and how can it be solved??? "
> 
> for more details I added 2 video to explain the problem if we can solve it as soon as possible it will be great
> 
>  WhatsApp.Video.2024-08-09.at.19.09.19_a2b24e28.mp4 
>  WhatsApp.Video.2024-08-09.at.19.09.31_4d18310d.mp4 
> thank you

![image](https://github.com/user-attachments/assets/fba624ad-5ab4-4793-a9a1-954377766ba4)

You are using the Mawaqit App from your SmartTV and it clearly says Wi-fi is not connected as you can see on the screenshot. Thats why it always shows not connected on the app try to connect your TV to your wifi. @MoathALATTAR

**Comment by MoathALATTAR** [comment]
Selam 

my brother mawaqit normally work without any problem if there are not internet connection the freezing happened while mawaqit app working normally in the mornig

**Comment by ghassenbenzahra123** [comment]
> Selam
> 
> my brother mawaqit normally work without any problem if there are not internet connection the freezing happened while mawaqit app working normally in the mornig

Hes on the legacy mode brother it does not work properly offline. You should use the normal app mode just disable this option on the settings menu. @MoathALATTAR 

![Capture](https://github.com/user-attachments/assets/e621766f-4bf4-47d5-b080-068a74c7a6cf)
