### ISSUE TITLE
Add the Indonesian language

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1278]
we have control and approved the Indonesian language with Fian brother form Indonesia 
and it is ready in crowdin

![image](https://github.com/user-attachments/assets/791c425a-0ac5-4604-b8ba-8043cca39019)

this is the related file

[MAWAQIT For Android TV (id).zip](https://github.com/user-attachments/files/16643935/MAWAQIT.For.Android.TV.id.zip)

if that possible can you add it in the next app version

**Comment by ghassenbenzahra123** [comment]
@MoathALATTAR 
The Indonesian language already exists on the app. We just need to apply the new crowdin updates. @ibrahim-zehhaf-mawaqit 

![Screenshot_1724342329](https://github.com/user-attachments/assets/221da05d-29b0-4db2-9523-b4bb03ffe6fb)
