### ISSUE TITLE
Random hadit language

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1283]
V 1.12.0-373

I don't know if this is a BUG, ​​but I have the Mawaqit language in Portuguese, the random hadits appear in Arabic.
When I go to the different language for random hadits menu and choose Portuguese, it starts showing the hadits in Portuguese. But if I don't put anything, it shows in Arabic.

Shouldn't the system automatically assume the system / backoffice language for hadiths?
In the backoffice the language is Portuguese.

In the app i don't have any language chosen or overridden.

![IMG_2852](https://github.com/user-attachments/assets/fc7b6609-175e-4f7e-aec6-69f82b09bc57)

**Comment by ghassenbenzahra123** [comment]
@MShoebPT 
The default hadith language is Arabic until you select another language from the hadith language settings.

**Comment by MShoebPT** [comment]
Thanks for the reply. @ghassenbenzahra123 
In previous versions it wasn't like that. It assumed the language that was defined in the backoffice.
I think it makes more sense as in previous versions.
If I put the system in Portuguese, it makes sense to have the hadits in Portuguese by default or in the language that is in the backoffice.
If i want to change it, then go to the hadit language menu on the Android box and change it.
This is my opinion.

**Comment by MShoebPT** [comment]
Another thing I noticed is that whenever the TV box is turned off and when it is turned on again, the hadits return to Arabic even I had previously changed the language in the hadit language menu.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ko on 1.15 please fix
