### ISSUE TITLE
Wake up before fajr feature has not been implemented on the AndroidTV

### ISSUE THREAD

**Issue by ms92asn** [mawaqit/android-tv-app#1293]
![image](https://github.com/user-attachments/assets/7309c26a-41b4-4ec8-b97a-f922dc297ca8)

When the parameter "Wake up before fajr (minute)" is not null, there is another adhan before the real adhan with the inscription "essalatou khayroun mina mawm"

![essalatoukhayounminamewm](https://github.com/user-attachments/assets/86926846-b86d-4ba2-bf93-d4b649c4c83a)

**Comment by ghassenbenzahra123** [comment]
@ms92asn 
The Wake up before fajr feature works properly but you are using the legacy mode app. Please disable it from the settings menu and you can see its results in the normal app mode.

![360538587-e621766f-4bf4-47d5-b080-068a74c7a6cf](https://github.com/user-attachments/assets/4477f572-acd5-400c-835e-cdee1c4e982f)

**Comment by ms92asn** [comment]
Sorry but it doesn't work in normal mode, I'm not in legacy mode
I use 2 differents devices in my home : 
- android box in normal mode ❌
- raspbery pi3 ✅

**Comment by ghassenbenzahra123** [comment]
Fixed in latest released version.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes tested by myself as well and it's ok
