### ISSUE TITLE
Issue with Iqamah Times Display for Mosque ID 14159

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1296]
A brother reached out to us requesting that Iqamah times be entered as a fixed schedule because he does not want the "+" symbol to appear anywhere on the screen. The Iqamah times in his mosque are fixed for all prayers except Maghrib, which is set 4 minutes after the Adhan. The times for August and September were entered as per the attached schedule, and they appear correctly for all prayers except Maghrib. Despite entering the times in the schedule as a specific hour, they are displayed as "+0" on the screen instead of showing the actual time.

[E-8.csv](https://github.com/user-attachments/files/16791645/E-8.csv)
[Ee-9.csv](https://github.com/user-attachments/files/16791646/Ee-9.csv)

![image](https://github.com/user-attachments/assets/bebbeae6-4d2e-4d1b-9c53-58932f29653b)

How can we resolve this issue to reactivate the mosque's system?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Already done on backend and will be deployed soon insh'Allah, an option will be available to force hh:mm format for iqama
