### ISSUE TITLE
Vertical mode - picture must not fit the screen vertically 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1320]
![IMG_3950](https://github.com/user-attachments/assets/5c122d58-df37-4b44-956a-62f40c2094c7)

**Comment by MShoebPT** [comment]
And btw neither from vertical to horizontal.
I uploaded some images on a screen that is vertical in Mosque ID 6369 and if people see it on a horizontal screen it looks like this.
![set_2024](https://github.com/user-attachments/assets/c15ac7ae-8e7b-4902-b0ab-0356b8b99c7f)
![IMG_3226](https://github.com/user-attachments/assets/cac47abb-beb9-409a-836e-0f26ef566e32)
