### ISSUE TITLE
Add or Update these language in Mawaqit TV Albanian, Bosnian and Montenegrin (Latin) languages

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1321]
Selam Aleykum

we have control and approved these languages with kujitim brother form Montenegro
and it is ready in crowdin

![image](https://github.com/user-attachments/assets/7958c4ce-0f8b-4a95-9e06-e6ae334197f4)

![image](https://github.com/user-attachments/assets/55006998-67ff-498e-9910-677b7e4cff1a)

![image](https://github.com/user-attachments/assets/1776a382-91e5-401e-b141-26a4bb2e1085)

if that possible can you add it in the next app version

Jazakum Allah khair

**Comment by MoathALATTAR** [comment]
@ghassenbenzahra123 

Alama aleykum 
brother 

in the last update in mawaqit tv app 

we cant find Montenegrin langauge 

did you add it?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ghassenbenzahra123 check please
