### ISSUE TITLE
Add or Update Portuguese in Mawaqit app 

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1323]
Selam Aleykum

the Portuguese  language in controled and it is ready in crowdin
![image](https://github.com/user-attachments/assets/0e73eb31-95d6-4020-b104-4fa5a538c81b)

I think it should be synic or update in the app

if that possible can you add it in the next app version

Jazakum Allah khair

**Comment by ibrahim-zehhaf-mawaqit** [comment]
already done
