### ISSUE TITLE
Corriger une traduction

### ISSUE THREAD

**Issue by ghadesmh** [mawaqit/android-tv-app#1342]
### What page(s) need to be updated?
إجراءات/ضبط/ضبط مواقيت الصلاة/حساب أوقات الصلوات/تحديد المواقيت
[Provide a list of URLs.](https://mawaqit.net/ar/backoffice/mosque/
إجراءات/ضبط/ضبط مواقيت الصلاة/حساب أوقات الصلوات/تحديد المواقيت
### Why is this update needed?
Corriger une traduction : La traduction proposée sur le site de la mise à jour **Fixation** du Dhuhr x minute avant Asr est إصلاح alors qu'elle doit être comme la Fixationdu Fajr et la Fixation du Isha = تحديد

If yes, please explain why.
![Fixation des horaires Fr-Ar](https://github.com/user-attachments/assets/b13976f9-5ddc-4d92-9b96-3eb7faa67301)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
It's a backend issue I will create it
