### ISSUE TITLE
getting api key to run the app localy

### ISSUE THREAD

**Issue by atefBB** [mawaqit/android-tv-app#1349]
I can't find a way to get `api key` mentioned in the setup docs [here](https://github.com/mawaqit/android-tv-app/blob/main/docs/setup/setup.md#running-the-app). Am I missing something ? I'm trying to run the app on `chrome` but without any success, any help would be appreciated. جزاكم الله خيرا

**Comment by ghassenbenzahra123** [comment]
@atefBB Please visit [https://mawaqit.net/api/2.0/me](url) and insert your mawaqit account credentials 
and you will get your api access token as shown in the attached screenshot.

![image](https://github.com/user-attachments/assets/4145d523-0e88-46e6-9e72-b79e1b596c11)
