### ISSUE TITLE
the next Salah is highlighted for 28178 

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1352]
there is one issue 

if you look at the time it is 5:21pm

Asr jamaah is at 5:30

but after the Asr starting time has passed the next Salah is highlighted although Asr Jamaah is still to happen

Is it possible to change so the next Salah is highlighted only after the Jamaah time
![WhatsApp Image 2024-10-02 at 22 53 01_65706228](https://github.com/user-attachments/assets/da1abf0a-dc2e-4c1a-91ac-c38a8ed1fd89)

**Comment by ghassenbenzahra123** [comment]
@MoathALATTAR  Do you mean to highlight only the next Salah after the Salah duration? It seems you've attached the wrong screenshot, as it doesn't match your description.

**Comment by MoathALATTAR** [comment]
Selam 

yes sorry I uploaded wrong picture 

this is the right one for different time
![2](https://github.com/user-attachments/assets/2f17d8d3-5018-41d5-a089-2dc92d181df2)
![1WhatsApp Image 2024-10-03 at 12 46 32_5a6f2324](https://github.com/user-attachments/assets/d03f3698-49d8-449f-904f-c2e62a593ae4)


check that Pls

Thanks
