### ISSUE TITLE
Background for Hadith

### ISSUE THREAD

**Issue by FirasTelmoudi** [mawaqit/android-tv-app#1353]
السلام عليكم ورحمة الله
Is it possible to have the old background for hadith or maybe an option to choose one of which![IMG_20241002_182807.jpg](https://github.com/user-attachments/assets/b224bd4a-534e-46b9-80bb-5092325cb3ef)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Wa alaik essalam, no it's not possible sorry

**Comment by FirasTelmoudi** [comment]
Sorry to hear that, kinda liked the old one with the Masjed background
