### ISSUE TITLE
Proposal for Activating Funeral Prayer Announcements in Mosques (From the brothers in Kuwait Mosques)

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1356]
We would like to propose adding a special service for announcing funeral prayers in mosques where these prayers are held. This proposal suggests dedicating a section in the app or on the smart screens to display information about the prayers during which funeral prayers will take place.

Key elements of the proposal:

Display of Funeral Prayer Times:
Specific prayers in which the funeral prayer will be held should be highlighted, with special timing indicated for funeral prayers. This information would be displayed after the obligatory prayers and throughout the day, helping to inform the community of upcoming funeral prayers in the mosque.

Special Countdown for Funeral Prayers:
A countdown timer would be activated after the obligatory prayer, showing the time remaining until the funeral prayer starts, allowing attendees to be ready and participate on time.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
They can use the flash message
I think it's enough for the funeral prayer
