### ISSUE TITLE
Mawaqit Box not update

### ISSUE THREAD

**Issue by MShoebPT** [mawaqit/android-tv-app#1358]
I have one Mawaqit box and an update for the Mawaqit app (1.15.2) is available but it does not install via Google Play.
I had the same problem updating the pre-installed version to version 1.14.0-377.
I was only able to install the update via APK.
having to update via APK is not very viable since I intend to purchase 3 more boxes to place in the Mosque and to reach the TV I need a ladder.
I've also tried to "factory restore" the box but it still doesn't work.

![IMG_3400](https://github.com/user-attachments/assets/71ab0d78-0a97-4e4d-a0d8-edca4f48ab20)
![IMG_3401](https://github.com/user-attachments/assets/fea86965-8b7a-4911-a420-1ce3bfb04f45)

**Comment by MShoebPT** [comment]
I also tried to uninstall the Mawaqit app but it doesn't allow.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Please try to update with usb 
We are looking for a solution to solve this

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Working on it here https://github.com/mawaqit/android-tv-app/issues/1420
