### ISSUE TITLE
Scheduled listening(The user can chose the start time, the end time, the reciter, the sourate or random sourate)

### ISSUE THREAD

**Issue by ghassenbenzahra123** [mawaqit/android-tv-app#1359]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
* It doesn't work, the quran recitation doesn't start at the scheduled time 
* Why we have a play button before the recitation starts ?
* The icon in the play button is very small comparing to the other buttons
* The user preferences are not saved in the form, only the time is saved, recite, surah and the random check box are not saved when we open the popup again
* Text on the popup is very small
