### ISSUE TITLE
feat: add Design for Hafs to Match Warsh Style

### ISSUE THREAD

**Issue by YassinNouh21** [mawaqit/android-tv-app#1378]
The Hafs Quran to have the same design as the Warsh script, specifically incorporating the pink design element to ensure consistency across both styles. This will provide a uniform visual experience for users reading either script.

**Describe alternatives you've considered**  
One alternative could be using a different but complementary design element for Hafs. However, maintaining the same pink design would be the simplest and most consistent solution.

![image](https://github.com/user-attachments/assets/2105e6f9-008e-4665-b55a-8771afa7b866)

![image](https://github.com/user-attachments/assets/248592bf-439e-4eb2-8f4c-a815e23893ae)

**Comment by ghassenbenzahra123** [comment]
![Screenshot_1731073869](https://github.com/user-attachments/assets/8d4461dc-3618-4d94-8f84-6a9ccbe93340)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
change the config file to tv_config.json
