### ISSUE TITLE
Erreur de traduction 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1384]
Assalam Alaykoum

Un utilisateur nous signale une erreur sur le hadith suivant et nous a fourni la correction
![image](https://github.com/user-attachments/assets/211b1c78-0d4d-41b8-b509-1f1c71dabf74)

 > In Indonesia translate is:<br> Anas bin Malik berkata, rasulullah saw bersabda<br> Do'a tidak akan tertolak di antara azan dan berdiri untuk sholat
 <br><div>
<div dir="ltr">Pada Sel, 3 Sep 2024 12.47, Amine de MAWAQIT &lt;<a href="mailto:contact@mawaqit.net" rel="nofollow" target="_blank">contact@mawaqit.net</a>&gt; menulis:<br>
</div>
<blockquote style="margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex">
<u></u> <div dir="ltr"> <div style="color:transparent;font-size:0px;border:0;width:1px;margin:0px;padding:0px;border-width:0px!important;display:none!important;line-height:0px!important"></div> <table cellspacing="0" border="0" cellpadding="0" align="center" style="font-family:Helvetica,Arial,sans-serif;letter-spacing:0;width:100%;border-spacing:0;border-collapse:separate;table-layout:fixed"> <tbody> <tr> <td style="font-family:Helvetica,Arial,sans-serif;padding:0"> <table style="table-layout:auto;border-spacing:0;border-collapse:separate"> <tbody> <tr> <td style="font-fam

**Link:** [Conversation with samdisor@gmail.com](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900171711)

**Customer:** [samdisor@gmail.com](https://app.intercom.com/a/apps/piphhhai/users/66b550ef07b3756767184619/all-conversations)
**Customer ID:** 43757
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900171711) when this issue is closed.

**Comment by YassinNouh21** [comment]
Hi Ibrahim,

The hadith translation, including the Indonesian version, is fetched from the backend, so we don't have direct control over it. You'll need to coordinate with the backend team to update the translation.
