### ISSUE TITLE
Arabic style of of writing 

### ISSUE THREAD

**Issue by Aslamibrahim12** [mawaqit/android-tv-app#1388]
If possible to change the Arabic font style/arabic writings to a different one please. 
![74B48B43-93F5-41E5-80CA-FA28A2F5E726](https://github.com/user-attachments/assets/a5221dda-353e-4a04-8465-08d82f72f8a4)
![74B48B43-93F5-41E5-80CA-FA28A2F5E726](https://github.com/user-attachments/assets/8cc57174-bd5a-4f7c-8518-d79028d0e02f)
![da16269e-ab5b-4551-aeb5-19dd0e5b099c](https://github.com/user-attachments/assets/a2e21512-73c4-42c5-ab1a-73ed9b4200cd)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Sorry we wan't write ahadith with quran font
