### ISSUE TITLE
Screen is freezing when changing Quran Riwaya

### ISSUE THREAD

**Issue by anouarchattouna** [mawaqit/android-tv-app#1390]
- Mode `Reading`
- Riwaya `Warsh`
- Start reading
- Click (change riwaya) button `انتقل الى حفص`
=> nothing happens and screen is freezing
![WhatsApp Image 2024-10-29 at 10 47 04 AM](https://github.com/user-attachments/assets/b4e6da65-3975-4ec4-8dc0-216476127899)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
please can you provide us with the version and device model you are using

**Comment by anouarchattouna** [comment]
> please can you provide us with the version and device model you are using

this was on :
- google pixel 7
- android 14
- mawaqit v1.16.1-394

**Comment by YassinNouh21** [comment]
@anouarchattouna can u test it again at the latest version. it supposed to be solved
