### ISSUE TITLE
Inverted quotation marks for Arabic language

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1397]
Should be `<< ... >>` instead of `>> ... <<`

![Screenshot 2024-10-28 at 9 49 28 AM](https://github.com/user-attachments/assets/f3e85744-fa33-408a-972f-22d632431710)

This one il also missing the quotation mark in the end

![Screenshot 2024-10-28 at 9 52 25 AM](https://github.com/user-attachments/assets/d47fb512-244e-4d41-b487-042b9788e5e8)

**Comment by ghassenbenzahra123** [comment]
These hadiths are fetched from the backend file ar.xml @ibrahim-zehhaf-mawaqit
