### ISSUE TITLE
Update Arabic language in Mawaqit TV

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1399]
Selam Aleykum

we have control and approved Arabic language
and it is ready in crowdin

![image](https://github.com/user-attachments/assets/0259a15e-69d3-472b-8f72-5c380266623d)

if that possible can you add it in the next app version

Jazakum Allah khair

**Comment by ibrahim-zehhaf-mawaqit** [comment]
There are also mistakes in hindi, for example all words between {} should not be translated

![image](https://github.com/user-attachments/assets/89366a24-f4e8-4e9a-81c6-12f37f664ef9)

**Comment by MoathALATTAR** [comment]
@ibrahim-zehhaf-mawaqit 
Selam aleykum 

related to Arabic I checked it and it is okey right now 

and Hindi language was checked too from our brother Sayed from india
