### ISSUE TITLE
Update Hindi language in Mawaqit TV

### ISSUE THREAD

**Issue by MoathALATTAR** [mawaqit/android-tv-app#1400]
Selam Aleykum

we have control and approved Hindi language with Syed Atif brother form İndia 
and it is ready in crowdin

![image](https://github.com/user-attachments/assets/40d8ec7b-724d-4369-a632-0fd0f8f00944)

if that possible can you add it in the next app version

Jazakum Allah khair

**Comment by YassinNouh21** [comment]
@MoathALATTAR the current version is already updated
