### ISSUE TITLE
Navigation with remote control is not working anymore in Quran reading mode

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#1438]
The selection sticks on one direction button 
Tested on the official bx

**Comment by YassinNouh21** [comment]
i have tested, trying to reproduce it

![Uploading testing the workflow .gif…]()

but it didin't occur to me i am in 1.17.0+1

**Comment by YassinNouh21** [comment]
I tried to reproduce it. but it didn't give me the issue mentioned 

[preview](https://media.discordapp.net/attachments/991676465529761894/1311050703187349544/testing_the_workflow_.gif?ex=6747729d&is=6746211d&hm=333c73de9ec56284f11dd604d4be87a46f585d892476377215272e68b0f22715&=&width=1439&height=496)
