### ISSUE TITLE
29th FEBRUARY is replaced by 1st March in downloaded calendar 

### ISSUE THREAD

**Issue by YmaneMawaqit** [mawaqit/android-tv-app#1513]
> <div dir="ltr"><div dir="ltr">Thanks for getting back to us with your response.<br><br>I understand what could be done to solve this issue. We could just make the necessary changes in the prayer times configuration through the backoffice and get rid of the extra day in February. The issue being encountered while doing that is the February month already includes the day extra day so even if we exclude that in the CSV which we pre-populate it with, the interface is preventing us from proceeding without adding the timings for that day. Take a look at the screenshot below to know more.<div><br></div>
<div>
<img src="https://mawaqit.intercom-attachments-3.com/i/o/piphhhai/1299755448/cdea513e88c1c3770386629197f0/image.png?expires=1766016000&amp;signature=de1170456bf2aeba9c66428009fddd945e13fad189179b27209ad70c15479f09&amp;req=dSIuH857mIVbUfMU3Xa7hwlb7Uh2Y9BZjIlYM3XodgDCVqab9AU%3D%0A" alt="image.png" width="562" height="322" intercom-upload-id="1299755448_cdea513e88c1c3770386629197f0"><br><br>

**Link:** [Conversation with psislamilainen@gmail.com](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900174423)

**Customer:** [psislamilainen@gmail.com](https://app.intercom.com/a/apps/piphhhai/users/6540d16c79f6bde51056f372/all-conversations)
**Customer ID:** 29339
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/piphhhai/inbox/inbox/all/conversations/191381900174423) when this issue is closed.

<img width="906" alt="calendar bug" src="https://github.com/user-attachments/assets/2eca5721-2e88-400b-8e72-54693826fbbe" />

As you can see in the photo, when the year only counts 28 days on February, the date for the 29th is replaced by the 1st March, but the prayer times are those of the 28th February

**Comment by Attom08** [comment]
Salam aleykum,

We have been re-routed to the February calendar issue. Is the issue resolved?

Barak Allahu fikum.
