### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#199]
After Onboarding, a white screen appears instead of the mosque prayer times. 

(changing the mosque id doesn't solve the problem).

![Screenshot_2022-09-11-20-12-55-67_99c04817c0de5652397fc8b56c3b3817.jpg](https://user-images.githubusercontent.com/33727630/189542717-a07b92af-18fb-41bf-8326-e73a2c27a0a4.jpg)

**Comment by omar-cherif** [comment]
@ismaelAbogabal the webview cannot display anything, same result everywhere (white page):
- Mosque Prayer times
- Network Status
- Privacy policy
- Installation guide

**Comment by omar-cherif** [comment]
Here's the aida for that box :
[aida64_S905X4-OTT-TV-Box.txt](https://github.com/mawaqit/android-tv/files/9543295/aida64_S905X4-OTT-TV-Box.txt)

**Comment by ismaelAbogabal** [comment]
ok will handle this
