### ISSUE TITLE
Offline version Screen 2 : Alerts

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#219]
The Screen 2 is the one that will be displayed/triggered for the following events : 

1. Time for Adhan
2. Time for Iqamah
3. Turn off your phone screen

Figma designs for reference :
https://www.figma.com/file/9vwJRWAl9KfSGXzHoimp6x/Products?node-id=705%3A10381

**Comment by ismaelAbogabal** [comment]
@omar-cherif  the Figma URL link  is not working 
could you check it 
![image](https://user-images.githubusercontent.com/63953869/196439481-025b43f8-195b-4b1d-9f89-ee2e16eda300.png)

**Comment by omar-cherif** [comment]
@ismaelAbogabal Figma link updated
