### ISSUE TITLE
Offline version Screen 7 : Random Hadiths

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#223]
The Screen 7 is the one that will be displayed/triggered for the following events :

1. After the prayer is over, and the after salah dua's and azkar are over, we display a random hadith : 
This random hadith is displayed all the day (1 Hadith per day).
![image](https://user-images.githubusercontent.com/33727630/192479761-c9d0fd60-6ac5-4e70-9786-8972acd9b3ca.png)

Figma designs for reference :
https://www.figma.com/file/9vwJRWAl9KfSGXzHoimp6x/Products?node-id=705%3A10381

**Comment by ismaelAbogabal** [comment]
Salam @omar-cherif 

After reading the [prayer.js](https://github.com/mawaqit/backend/blob/master/src/AppBundle/Resources/public/prayer-times/js/prayer.js) file 
I found out that this screen is shown after azhan duaa and before the iqama countdown

Could you please confirm it or explain the logic of showing this a little bit further?

**Comment by ismaelAbogabal** [comment]
@omar-cherif, any updates brother
