### ISSUE TITLE
Offline version Screen 10 : Live streaming

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#226]
The Screen 10 is the one that will be displayed/triggered for the following event :

Mosques can have multiple displays, and can livestream the Jumua Sermon, or Duroos on multiple screens at once.
Mosques can stream using the GoPro HERO8 camera and link their Youtube Channel ID with MAWAQIT to broadcast live content to their followers.
Mosque Imams can create a Livestream using an upcoming version MAWAQIT App using their Smartphone.

Some Examples: 
- Livestreaming to the Women praying space
- Streaming to the Underground prayer room or any other mosque screens
- Streaming to the MAWAQIT App (Women at home who would like to watch the Jumua live streaming, or the Duroos)

![image](https://user-images.githubusercontent.com/33727630/192485458-1e1845c1-f875-4096-8ed4-1f8b5ca25945.png)
![image](https://user-images.githubusercontent.com/33727630/192486074-e3abbcd8-54c1-4b78-9375-cf5e316b0b3e.png)
![image](https://user-images.githubusercontent.com/33727630/192485220-d6998ab7-c491-4dca-acb8-2ef765d614ae.png)

Figma designs for reference :
https://www.figma.com/file/9vwJRWAl9KfSGXzHoimp6x/Products?node-id=705%3A10381

**Comment by omar-cherif** [comment]
@AnasElbattra Please add a streaming video placeholder to that page.
Also add the sub menu item.

**Comment by AnasElbattra** [comment]
I add jumua live in a drawer and create the associated screen 
I used the URL test from Youtube 
still, I need the URL from the backend

**Comment by omar-cherif** [comment]
@AnasElbattra Indeed, the value `jumuaStreamUrl ` is coming soon incha'Allah
