### ISSUE TITLE
Device Offline screen missing icon

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#233]
If the device is in offline mode The current offline screen Is missing the wifi logo image
![Screenshot_1667210354](https://user-images.githubusercontent.com/63953869/198982435-57985641-76d2-4f81-b12a-7cca848f8dfe.png)

**Comment by omar-cherif** [comment]
Your answer is here dear @ismaelAbogabal 
https://github.com/mawaqit/backend/issues/174

Please use the new mawaqit fonts file, and you will get all the icons you need.

**Comment by omar-cherif** [comment]
@ismaelAbogabal, I encourage you to implement and use the Mawaqit Icons attached in this Fonts file.
(The same fonts file used in Mobile App, which will be shared among all apps: Mobile, AndroidTV, and Backoffice).

If you need to display dark icons on a light background, you can use the dual color icons (purple + red or green).
If you need to display light icons on a dark background, force the white color to the icon, and superpose the icon-no-sign, or the icon-green-sign on top of it (one widget on top of the other).

Rearding the Wifi icon, it's not present in the current version of the font. I will add it to the MawaqitIcons-v1.17 and send you the new font file.

**Comment by omar-cherif** [comment]
@ismaelAbogabal Please find attached the MawaqitIcons-v1.16. You can start using it (Use a placeholder icon from this file, example: icon-no-sign).

I will add the No internet or No wifi icon in the upcoming  MawaqitIcons-v1.17 incha'Allah.

Sounds good?

**Comment by ismaelAbogabal** [comment]
Sallam 
I used the material Icon 'wifi_off_rounded'
Updated the UI to match the app design in dark and light modes. 

![Screenshot_1667305386](https://user-images.githubusercontent.com/63953869/199232181-6b25b2e3-9948-4882-a3a1-74454074b199.png)

![Screenshot_1667305398](https://user-images.githubusercontent.com/63953869/199232187-0fecb5ed-43cd-4b10-ad4b-ff0505f60423.png)

**Comment by ismaelAbogabal** [comment]
@omar-cherif

**Comment by omar-cherif** [comment]
@ismaelAbogabal Please use the latest version of the mawaqit-font containing the icon

**Comment by omar-cherif** [comment]
@ismaelAbogabal Please use the latest version MawaqitIcons-v1.18 here attached:
[MawaqitIcons-v1.18.zip](https://github.com/mawaqit/android-tv-app/files/10319824/MawaqitIcons-v1.18.zip)
![Group 1](https://user-images.githubusercontent.com/33727630/209964248-8f49eccb-d45c-49d8-aabd-37f98c231a96.png)

There you got the wifi icon, the no-wifi icon, you can use the bi-color one for better clarity.
Also, for dark backgrounds, you can superpose the no-wifi icon with (glyphs eb01 e9ac)
