### ISSUE TITLE
Cannot build on codemagic (Flutter 3.3.6)

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#234]
Hate to bring you bad news...
...but [android-tv [Default Workflow]](https://codemagic.io/app/620d135f8c8d2d3923271d81) build #85 (branch: offline-mode, workflow: Default Workflow | ) has failed with the following error:

Failed to build for Android
Check out the detailed build log [here](https://codemagic.io/app/620d135f8c8d2d3923271d81/build/6361598036dd12f898f6d306).

> Cannot build the current PR (branch offline
> 
> 
> Warning: The plugin flutter_inappwebview requires Android SDK version 33.
> For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
> Warning: The plugin url_launcher_android requires Android SDK version 33.
> For more information about build configuration, see https://docs.flutter.dev/deployment/android#reviewing-the-build-configuration.
> One or more plugins require a higher Android SDK version.
> Fix this issue by adding the following to /Users/builder/clone/android/app/build.gradle:
> android {
>   compileSdkVersion 33
>   ...
> }
> 
> ../programs/flutter_3_3_6/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.24.0/lib/src/firebase_app.dart:18:25: Error: Member not found: 'FirebaseAppPlatform.verifyExtends'.
>     FirebaseAppPlatform.verifyExtends(_delegate);
>                         ^^^^^^^^^^^^^
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script '/Users/builder/programs/flutter_3_3_6/packages/flutter_tools/gradle/flutter.gradle' line: 1159

**Comment by ismaelAbogabal** [comment]
Problem solved after commit db2a0803473c435acc89149b43891fa10451f6ef
