### ISSUE TITLE
Adjust the main screen widgets and texts size (to match the current online version)

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#235]
Please adjust all the offline version rows, columns, widgets, texts sizes to mach the current online version
![image](https://user-images.githubusercontent.com/33727630/200046267-84828fea-daaf-401c-aa58-20a67b31e819.png)

![image](https://user-images.githubusercontent.com/33727630/200046093-612c92ad-7892-4d3c-a8b8-f0a42c402c4f.png)
![image](https://user-images.githubusercontent.com/33727630/200046150-5e094ab0-43f1-42c0-aecc-84c0473cfb81.png)

![IMG20221104185732](https://user-images.githubusercontent.com/33727630/200046618-98154dd2-9705-4f62-a134-c22ed3b3bd82.jpg)
![IMG20221104185731](https://user-images.githubusercontent.com/33727630/200046623-4dff8b6d-8b3b-4ffc-9c42-66d10734727d.jpg)

**Comment by ismaelAbogabal** [comment]
Brother, please keep in mind The way the flutter handles the UI is entirely different from the CSS.
To make the application look the same on all screens I have to use flutter way.

**Comment by omar-cherif** [comment]
@ismaelAbogabal The text sizes are not the same.
Exemple : The current time is way smaller that the online version.

Please adjust all the text sizes to match the online version.

**Comment by omar-cherif** [comment]
@ismaelAbogabal Is this issue still open ?
