### ISSUE TITLE
Android TV Error UI 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#236]
Android TV application should show an error UI in case 
- The mosque is entirely missing from the database 
- There is an error in getting the mosque data and there are no cached value

**Comment by omar-cherif** [comment]
@ismaelAbogabal this issue is still present in the current offline version.
Could you please check? Baraka'Allah fik.

**Comment by omar-cherif** [comment]
@ismaelAbogabal Could you please be more specific, or send an example (i'll help you fixing and i8n the texts).

**Comment by omar-cherif** [comment]
@ismaelAbogabal ?

**Comment by omar-cherif** [comment]
@ibrahim-zehhaf-mawaqit when a mosque is 'Suspended' or 'Closed' or 'Temporary Closed or Closed for Administrative reasons'.
Does the backend send an error like "Mosque non found" "This mosque no longer exists", etc?.

**Comment by omar-cherif** [comment]
☝🏻 Question for you @ibrahim-zehhaf-mawaqit

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes all the apis will return a 404 not found status 
Please see the swagger

**Comment by ismaelAbogabal** [comment]
ok will work on distinguishing these errors 
- mosque not found on the screen 
- mosque data error (if there are any conversion errors when converting the mosque JSON into mosque data class)
- No internet error (if there are no internet or cached values)

**Comment by omar-cherif** [comment]
@ismaelAbogabal is this issue still open ?

**Comment by omar-cherif** [comment]
@ismaelAbogabal ? is this issue still open ?
