### ISSUE TITLE
The application always starts on the onboarding screen 

### ISSUE THREAD

**Issue by AnasElbattra** [mawaqit/android-tv-app#240]
The onboarding screen should only be visible when the user uses the app for the first time

**Issue**
The application always starts on the onboarding screen 

**Solution steps**
- Make sure the mosque UUID is saved in shared preferences 
- Mosque data is fetched on the initial app launch

**Comment by ismaelAbogabal** [comment]
this is fixed on the commit 5f0ce07097cd4e3568485280025c6b6d76d10544
