### ISSUE TITLE
Add a sub menu (placeholders) to the the drawer menu of the offline version

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#253]
Please add a placeholder for each Screen to be able to test and switch between them manually during development.

- Screen 1 (Prayer times)
- Screen 2
- ...
- Screen 10 (Streaming)

Please add a placeholder page for each of those screen in this sub-menu.

**Comment by omar-cherif** [comment]
@ismaelAbogabal Could you please add this secret sub-menu to the offline-version so we can switch between those during dev ? Chokran !

**Comment by ismaelAbogabal** [comment]
Moved to #262
