### ISSUE TITLE
Drawer menu: Black screen when hovering the offline menu item 

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#254]
A black screen appears as soon as we hover the Offline mode menu item.

**Comment by omar-cherif** [comment]
@AnasElbattra @ismaelAbogabal here's the video :

https://user-images.githubusercontent.com/33727630/210174927-bf879894-2205-4f4d-98e0-7d617a7e0876.mp4

**Comment by AnasElbattra** [comment]
@omar-cherif this issue doesn't appear on my devices
