### ISSUE TITLE
Iqama : Iqama Triggers 60 seconds in advance

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#255]
Trigger the Iqama at countdown 00:00 and not 00:59

See video attached:
 https://user-images.githubusercontent.com/33727630/210175505-e53195aa-e334-4bfe-8b70-2fc41a50f4eb.mp4

**Comment by AnasElbattra** [comment]
@omar-cherif  please send me the mosque name for this issue because search by id not working

**Comment by AnasElbattra** [comment]
@omar-cherif  this issue is tested on mosque id 256 and 1847  and is working perfectly
