### ISSUE TITLE
compileSdkVersion 33

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#257]
![building_android.log (1).txt](https://github.com/mawaqit/android-tv-app/files/10329445/building_android.log.1.txt)

**Comment by AnasElbattra** [comment]
@omar-cherif  try build with this command :  flutter build appbundle --release --no-tree-shake-icons

**Comment by omar-cherif** [comment]
@AnasElbattra

This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:

- file:///Users/builder/clone/lib/src/pages/home/widgets/WeatherWidget.dart:21:26



FAILURE: Build failed with an exception.


* Where:

Script '/Users/builder/programs/flutter_3_3_10/packages/flutter_tools/gradle/flutter.gradle' line: 1159


* What went wrong:

Execution failed for task ':app:compileFlutterBuildRelease'.

> Process 'command '/Users/builder/programs/flutter_3_3_10/bin/flutter'' finished with non-zero exit value 1


* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.


* Get more help at https://help.gradle.org


BUILD FAILED in 1m 25s

Running Gradle task 'bundleRelease'... 87.3s

Gradle task bundleRelease failed with exit code 1



Build failed :|

Failed to build for Android


Publishing

< 1s

Cleaning up

< 1
