### ISSUE TITLE
Adding voice adhan into the TV version of the app 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#282]
@omar-cherif 
We thought that it would be logical to add adhan's voice 
In the case of people using the mawaqit android TV app 

I know that we have this feature on the mobile 
So if you think we should add this feature to the Tv version of our app 

Please provide us with the information you have from your past experience with the mobile app

**Comment by ismaelAbogabal** [comment]
Also in the future 
Thanks to the excellent effort from @AnasElbattra we can add Quran voice during the day 
What do you think about it

**Comment by omar-cherif** [comment]
@ismaelAbogabal Baraka'Allahu for this issue. Indeed, the Adhan is mentioned in the Notion documentation sent yesterday.
