### ISSUE TITLE
add hijri date config

### ISSUE THREAD

**Issue by AnasElbattra** [mawaqit/android-tv-app#325]
![image](https://user-images.githubusercontent.com/75434006/212367317-be2abe1a-73f4-4566-9b04-34825c1f1826.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @omar-cherif @ibrahim-zehhaf-mawaqit how can I get the language code to translate the date ![image](https://user-images.githubusercontent.com/75434006/212367678-fda7210b-0c7d-478d-95d0-7b332eeccde4.png)

Oh yes, the code is a concatenation of the language code chosen by the user on the android TV app and the country code of the mosque sent by /info api (We will add it insh'Allah) in this issue https://github.com/mawaqit/backend/issues/252

[LANG]-[COUNTRY-CODE]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> > @omar-cherif @ibrahim-zehhaf-mawaqit how can I get the language code to translate the date ![image](https://user-images.githubusercontent.com/75434006/212367678-fda7210b-0c7d-478d-95d0-7b332eeccde4.png)
> 
> Oh yes, the code is a concatenation of the language code chosen by the user on the android TV app and the country code of the mosque sent by /info api (We will add it insh'Allah) in this issue [mawaqit/backend#252](https://github.com/mawaqit/backend/issues/252)
> 
> [LANGUAGE-CODE]-[COUNTRY-CODE]

@AnasElbattra the countryCode il already present in /info api
