### ISSUE TITLE
three configs are missing from the config/API

### ISSUE THREAD

**Issue by AnasElbattra** [mawaqit/android-tv-app#327]
![image](https://user-images.githubusercontent.com/75434006/212374708-3fba84d0-115a-4fee-8dfe-94ea0dfbb34e.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok @AnasElbattra added here https://github.com/mawaqit/backend/issues/252 the third one (Display prayers...) is no longer used
