### ISSUE TITLE
Missing Logo (right/left Mosque title)

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#331]
Please replace the placeholder by the real mosque Logo.

![IMG_20230113_222301.jpg](https://user-images.githubusercontent.com/33727630/212421798-b367bc61-9f1c-4862-bb9d-32692eea6a93.jpg)

![IMG_20230113_222243.jpg](https://user-images.githubusercontent.com/33727630/212421822-83b22095-dfb9-4130-80aa-611391f62c26.jpg)

**Comment by AnasElbattra** [comment]
@ibrahim-zehhaf-mawaqit  How can I get the logo?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @ibrahim-zehhaf-mawaqit How can I get the logo?
In the /info response api

![image](https://user-images.githubusercontent.com/97339607/212539414-591e9ab5-3719-48af-9097-acd738dd4063.png)
