### ISSUE TITLE
Missing footer content

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#338]
In the offline version, footer content (bank details for this mosque) are missing. 

![IMG_20230116_143030.jpg](https://user-images.githubusercontent.com/33727630/212689971-182c47dc-7c7d-4ea4-a904-f2ab14aca76d.jpg)

![IMG_20230116_143009.jpg](https://user-images.githubusercontent.com/33727630/212689988-dc3c475a-b593-435a-8fd8-4946ff0d6067.jpg)

**Comment by AnasElbattra** [comment]
@ibrahim-zehhaf-mawaqit  how can I get bank information 
![image](https://user-images.githubusercontent.com/75434006/212752837-6198eb35-a7f8-4805-b6d6-3fa013897f3c.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@AnasElbattra we will no longer show this info on the screen.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Show only the association name and phone number if exist
