### ISSUE TITLE
Missing footer content (BANK DETAILS)

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#352]
Assalamu Alaikom, 
Could you please add the mosque Bank account details in the footer? 
Baraka'Allahu fikom! 

![IMG_20230117_181933.jpg](https://user-images.githubusercontent.com/33727630/212967901-826807c5-7392-4bb1-bdc4-665bf4dd6114.jpg)

![Screenshot_2023-01-17-18-21-34-00_99c04817c0de5652397fc8b56c3b3817.jpg](https://user-images.githubusercontent.com/33727630/212968064-81a22449-0744-449b-bf86-9058c765ed4a.jpg)

**Comment by AnasElbattra** [comment]
@omar-cherif  

![image](https://user-images.githubusercontent.com/75434006/213020605-f059d18c-a554-46ec-9e59-e7e22f2d4d9a.png)

**Comment by omar-cherif** [comment]
@ibrahim-zehhaf-mawaqit can we close this issue for now?
(could you please create that feature request on the backend? Baraka'Allahu fik)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
No don't close it
We still showing association name and phone number 

the bank account is a confidential information witch we have to protect

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Sorry if this issue is for the bank account only yea you can close it
