### ISSUE TITLE
Small texts

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#354]
Very small texts

![IMG_20230117_183549.jpg](https://user-images.githubusercontent.com/33727630/212971969-ff918f9d-4ce2-46d5-b8a7-264fa5587d8f.jpg)

**Comment by AnasElbattra** [comment]
@omar-cherif  Not as it appears to me

![image](https://user-images.githubusercontent.com/75434006/213023038-9afef2dd-c77a-40e4-834c-8269e8a5d801.png)

**Comment by omar-cherif** [comment]
OK, will close this issue for now if we cannot re-produce it again.
We'll re-open it if needed.
