### ISSUE TITLE
Announcements screen: Add translation string for when no announcements

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#366]
When no announcements, get the i8n from Crowdin.

![IMG_20230118_220953.jpg](https://user-images.githubusercontent.com/33727630/213295523-9a82885a-ca10-4e90-98af-6144eb565897.jpg)

**Comment by AnasElbattra** [comment]
@omar-cherif this string is for testing only, as for the actual app if no announcements will show a normal screen
like this :
![image](https://user-images.githubusercontent.com/75434006/213465611-c4bccb18-d42d-416c-92ca-33f8fe806346.png)
