### ISSUE TITLE
Bashkir language need to be added into config.dart file 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#382]
# Issue 

- Bashkir language needs to be added into src/data/config.dart file
- Missing logo of Bashkir language

![image](https://user-images.githubusercontent.com/63953869/213879913-0ddab372-8438-4260-bfb1-dd1eea76ac34.png)

**Comment by ismaelAbogabal** [comment]
@omar-cherif can you please hand me the image logo of this language

**Comment by omar-cherif** [comment]
OK @ismaelAbogabal  added the ba.png file to the offline-mode branch /assets/img/flag/
