### ISSUE TITLE
Cache image 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#431]
It would be great if mawaqit supports caching for the image 

this feature can be easily achieved using the CachedNetworkImage plugin

**Comment by omar-cherif** [comment]
Which image @ismaelAbogabal are you referring to?
Could you be a bit more specific? 🙏🏻 Chokran

**Comment by ismaelAbogabal** [comment]
- The background image of the offline home screen
- the QR image 

I don't want to be specific so when any team member(me or anas) start working on this issue 
he will search himself for the non-cached images

**Comment by omar-cherif** [comment]
I see, yes please include it to cache the images the app is requesting or will request in the future (as we are on a continuous improvement streak).

Baraka'Allahu fikom!
