### ISSUE TITLE
The temperature is not good, i have 46c in paris 🙂 and the icon is not ok also

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#459]
@ibrahim-zehhaf-mawaqit 
Temperature is coming from the backend server 7c we directly showed it in the UI 

![image](https://user-images.githubusercontent.com/63953869/216298152-40a6f238-f764-4209-8a14-97acc0f31eca.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok I don't know why I had 46c on the TEST mosque testerday I will recheck

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal 
I use this css file https://github.com/mawaqit/backend/blob/master/src/AppBundle/Resources/public/weather/weather-icons.min.css to get the icon

Here is the pattern 
<i style="color: #FFF;" class="wi wi-[time]-[iconFromTheWeatherApi]"></i>

so to build the css class I have two variables
time = day or night 
  * day if we are between fajr and maghrib 
  * night  if we are between maghrib and fajr
iconFromTheWeatherApi = take the icon value from the api response

For example
<i style="color: #FFF;" class="wi wi-day-cloudy"></i>

For the color I have explained it in the notion documentation

Please tel me if it is not clear
