### ISSUE TITLE
Adan countdown sec is displayed

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#475]
Sec written (not in arabic). 
![IMG_20230203_152609.jpg](https://user-images.githubusercontent.com/33727630/216628195-3b051eef-5a30-4294-a73f-e2b08b50663d.jpg)

**Comment by AnasElbattra** [comment]
@omar-cherif  I need to "sec" string on crowdin

**Comment by omar-cherif** [comment]
@ismaelAbogabal

**Comment by ismaelAbogabal** [comment]
@omar-cherif 
could you please checkout the GitHub configuration of the crowdin is done in the main branch or offline-mode
