### ISSUE TITLE
Token not working 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#480]
All backend endpoints return 403 status code 

![image](https://user-images.githubusercontent.com/63953869/216647668-d7b171dc-1b4b-4e3a-bcdb-47337ce7c570.png)
Please check it out and tell me what to do

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes sorry it's because of the api quota is reached
I put an unlimit quota for your token
It's ok now, Try again, if the pb persists, tel me, so i can purge the cache

**Comment by ismaelAbogabal** [comment]
Perfect its working now

**Comment by youcci** [comment]
Where can I get an API Key?

**Comment by atefBB** [comment]
> Where can I get an API Key?

السلام عليكم
I wanna to get API key too but the docs doesn't mention how to do exactly !
