### ISSUE TITLE
In the home screen date widget show moon image instead of moon icon 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#489]
The moon image used in the javascript version is much better looking than the icon 
  
![image](https://user-images.githubusercontent.com/63953869/216773024-9c2c8020-ae48-4e81-aceb-0327c00aaca1.png)

It would be better if we had this in the app 
@omar-cherif What do you think?

**Comment by omar-cherif** [comment]
@ismaelAbogabal Please use icon anyway (font). We are avoiding png format. 

We'll improve the icon later.

**Comment by ismaelAbogabal** [comment]
Ok
