### ISSUE TITLE
Iqama alert : fix fr translation of the text "turn your phone in silent mode"

### ISSUE THREAD

**Issue by AnasElbattra** [mawaqit/android-tv-app#496]

**Comment by ismaelAbogabal** [comment]
@omar-cherif  please confirm if this is a valid translation 'mettez votre téléphone en mode silencieux' so i add it to crowdin

**Comment by omar-cherif** [comment]
Veuillez mettre votre téléphone en mode silencieux

Best regards,
*Omar CHERIF*
Co-founder, COO at MAWAQIT.net

Connecting Muslims to Mosques
https://mawaqit.net
[image: Facebook] <https://www.facebook.com/Mawaqit-878834798944718/> [image:
Twitter] <https://twitter.com/MawaqitTeam> [image: Youtube]
<https://www.youtube.com/channel/UCK0bHMvAlVL8NvyofiMulUw/>

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The fr translation still ko
Veuillez tourner vos téléphones portables

**Comment by ismaelAbogabal** [comment]
Fr translation now is working just fine
