### ISSUE TITLE
Failed host lookup: 'mawaqit.net'

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#507]
@ibrahim-zehhaf-mawaqit 
it seems my personal IP address has been blocked from using the API 
because when request any endpoint I get 
`Failed host lookup: 'mawaqit.net' (OS Error: No address associated with hostname, errno = 7)`

please check it out and tell me what to do

**Comment by ibrahim-zehhaf-mawaqit** [comment]
we had a downtime arround 3:30 pm FR
you still have the pb  ?

**Comment by ismaelAbogabal** [comment]
yes still have it 
![image](https://user-images.githubusercontent.com/63953869/216827370-9a18ec8e-d69f-4f05-8d36-7169a9b76579.png)

With VPN I get a response 
![image](https://user-images.githubusercontent.com/63953869/216827430-65cbfda5-6856-4ef0-8944-921bfa4ec8d9.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I think it's just your local DNS cache, try to restart your network or reboot the computer

**Comment by ismaelAbogabal** [comment]
working fine now 

> I think it's just your local DNS cache, try to restart your network or reboot the computer
