### ISSUE TITLE
Athkar screen is not respecting the specifications (sliding, text size, translation with phonetic, duration)

### ISSUE THREAD

**Issue by AnasElbattra** [mawaqit/android-tv-app#516]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
there are still things to fix

- [ ] every duaa Must be displayed during X seconds which chosen by the admin, please don't check the feature in the notion document if is not verified 
![35C4DCE3-A431-4158-865F-D3358758437D](https://user-images.githubusercontent.com/97339607/220896101-75933c4c-2516-4587-8d11-fca437acad59.jpeg)

- [ ] Some duaas are missing like the kursi verse and others 
- [ ] Some duaas are displayed twice or more

**Comment by ibrahim-zehhaf-mawaqit** [comment]
fixed

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Still ko on v1.1.22

**Comment by AnasElbattra** [comment]
@ismaelAbogabal please check it

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
The durations has been fixed in this commit  ae1b82a08377c7b5402710676daed49e162045a2
