### ISSUE TITLE
Jumua is not handled (not highlighted i have shuruq highlighted instead , countdown not ok, no thikr ...etc)

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#536]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Still not ok
Please close the issue only if you are sure that you've fixed it 
The jumua Hadith reminder is not displayed at 12 o'clock which is the jumua1 tume for TEST_MAWAQIT mosque 

![4700F981-0C66-415F-87AD-F1B02E2F9B0A](https://user-images.githubusercontent.com/97339607/220917482-60d3ef04-408c-4d1a-ad07-cf4b4d8b2757.jpeg)
