### ISSUE TITLE
Messages are not displayed correctly, every time only one message is displayed, we must have all the messages sliding one after one until the end

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#540]
show all announcements one time

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The duration is not respected
![60197F21-1BE0-4917-B8DA-949DCAC97A2D](https://user-images.githubusercontent.com/97339607/220905404-5769724a-abaa-4120-8aba-ab0468e60347.jpeg)
