### ISSUE TITLE
Random Hadith: 1 Hadith per hour

### ISSUE THREAD

**Issue by omar-cherif** [mawaqit/android-tv-app#570]
The random hadith that we see during the day shouldn't change.
Please set the random hadith to stay all day, and to change the next day.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
No 
Not a hadith per day
The hadith is cached by cloudflare so you can fetch a Hadith every time you display the hadith screen, the same one will be displayed during one hour

**Comment by omar-cherif** [comment]
@ismaelAbogabal, Please make sure to take into consideration Ibrahim's information above.
Don't hesitate if the behavior as described by Ibrahim is still not 100% clear. Baraka'Allah fik.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit So caching should be handled from Cloudflare Should I do anything right now?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Why you close it ? Please wait for my reply when you ask me a question

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes the Hadith is cached 1 hour by cloudflare so it should be the same for one hour if you call the api with same query strings 
But when i observe the behavior is not good.

The

**Comment by omar-cherif** [comment]
@Ismael could you please handle this issue today? BarakAllah fik.

**Comment by ismaelAbogabal** [comment]
Remove all the caching logic from the flutter side and relay 100% on cloud flare
- One API call per screen so random hadith don't change ever on a single page
