### ISSUE TITLE
Use the new api get by id instead search

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#594]
Please rollback to search  by ID if the user know it or key word otherwise

Use this API for get by ID 

![image](https://user-images.githubusercontent.com/97339607/221409917-ea29081a-7b03-4924-ac9a-e38247751dc9.png)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
 API response is missing the UUID please add it so we can use it in the other API endpoints 

```json
 {
"id": 1, 
"name": "Mosquée TEST, type: MOSQUE, localisation: 1 rue Berthier 91350 Paris France", 
"image": "https://mawaqit.net/upload/mosque/60/50/49/60504962093be883884330.jpeg"
}
```

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Added 
![image](https://user-images.githubusercontent.com/97339607/221519153-b2f39b7a-ec9b-4d23-925e-3361f523eac4.png)
