### ISSUE TITLE
I can't select the first card on the search result list

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#598]
Ko when the language is arabic

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Not ok on v1.1.22

**Comment by ibrahim-zehhaf-mawaqit** [comment]
It's not working correctly in other language too
Please find a solution we are blocked and can't select a mosque

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I think it's random

**Comment by ismaelAbogabal** [comment]
I test with my keyboard in 
- Arabic 
- English 
- French 

And it worked from my side 

Will test it on my TV Box

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok but on my side it blocks sometimes
@omar-cherif have the same pb ?

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Sometimes there is a little difference in behaviour between boxes 
What is the type of TV box you are using?

**Comment by omar-cherif** [comment]
We need a Crowdin sync please @ismaelAbogabal, brothers from the translation team are coming and adding more languages.

Can we kind automate it like before?
The language syncs once per day for example, and a pull request is created automatically and assigned to the @Quality Assurance team so they can test the new language and make sure everything works fine, and that there're no regressions in the App display with those new strings. (sometimes other languages strings are longer, or get truncated, or RTL language is not correct etc. ) 

If it's approved by them, then it passes into a release candidate for the mobile team, so they can create a new scheduled deployment.

Sometimes, the PR & Marketing Team will also add some meta data to that new release (App store and Android store descriptions, keywords, title, store Images and screenshots...).

Baraka'Allahu fik in advance.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> @ibrahim-zehhaf-mawaqit Sometimes there is a little difference in behaviour between boxes What is the type of TV box you are using?

Xiaomi S

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Still have the problem 
![Uploading 7D1A90BB-2C0E-4764-87A4-4DB91260136E.jpeg…]()
