### ISSUE TITLE
When iqama is disabled the jumua2 and eid2 are hidden

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#607]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Still ko on v1.1.24

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salat al eid 2 is hidden also

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit this issue should be fixed on this commit a551a10dd55a1ae41ddc16a372c3b03cf8239bb8

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal the bug still present

**Comment by ismaelAbogabal** [comment]
Its working on the test mosque 

![image](https://user-images.githubusercontent.com/63953869/224568710-bd3c1e9c-7a88-464a-a93b-b29b307adbbb.png)

@ibrahim-zehhaf-mawaqit what is the mosque you are using for test?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes this mosque id 1
Do you see that jumua2 and eid2 are not displayed ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok this the pb, it's not a good behavior

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
Sorry I thought this was the desired results

**Comment by ibrahim-zehhaf-mawaqit** [comment]
No pb brother, I m waiting the fix

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This issue was fixed on this commit ab187cb0fa558a89e7e13c64e8922accd2b0ab34

Now wither the iqama is enabled or disabled the eid2 and jumuaa2 will be visible
