### ISSUE TITLE
The jumua Hadith reminder must display at exactly the jumua time and not before 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#608]
It's displayed 5 min before the jumua time 
![5F4A9C60-66D8-4B05-B1BB-31D7EA1A5490](https://user-images.githubusercontent.com/97339607/221846031-451471a6-4623-45f3-b64c-c2b419c6dcc7.jpeg)

and 5 minutes later the black screen appears 

the behavior is not good, please see the notion document 
![444C6774-4616-4087-8559-EC61BC9721DD](https://user-images.githubusercontent.com/97339607/221848276-22336b7e-1093-4883-914c-fddfc5bace09.jpeg)

One screen can be displayed at one time 
Black screen or reminder screen not both

so if both are enabled the black screen is more priority 

The jumua screen must stay during the time chosen by the user, i observe less than 10 min instead of 20 min 
![F8E994D9-32EC-486B-B5D5-ED26344E29C1](https://user-images.githubusercontent.com/97339607/221849176-9a685980-1481-4137-ad91-aa284f9ae7b2.jpeg)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
We show a black screen during the salah time if the admin configured it as 'blackScreenWhenPraying'

Isn't this is the state with jumuaa pray?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
No for the jumua the behavior is different, for jumua just display the reminder or the black screen during the configured time

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This issue should be solved in this commit a8a51ad44291951f52008b70c3a0f8123aca99a5
