### ISSUE TITLE
No announcements when offline mode

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#609]
Please load all the announcements at the first start of the app and store them locally so if the box looses internet connection we still seeing the announcements 

every time the box is connected to the internet it synchronizes with the backend to get the new announcements

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
The announcement is loaded with the mosque info 
I test the announcement is showing when the app is in offline mode 

Tested on mosque 1

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Try this  to

1. clear the date of the app
2. Do the onboarding, and choose the mosque 
3. immediately after choosing the mosque, disable the WIFI
4. Observe 

This behaviour will be frequent in mosques which not have internet, they will juste share there smartphone hotspot to do the onboarding and stop sharing internet.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
When the user selects a mosque he has to wait until everything comes to the home screen before he closes the Connection

If he closed the connection immediately after selecting a mouse we will have undesired behaviour like

**Comment by ibrahim-zehhaf-mawaqit** [comment]
How the user know this ?
We have to add a loader to force the user waiting for the date loading

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Still ko for me but this can wait for a next release after ramadan

**Comment by ibrahim-zehhaf-mawaqit** [comment]
For example pictures are not loaded
