### ISSUE TITLE
After jumua time asr is not highlighted 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#614]
After the jumua countdown finished it changes to as but the jumua still highlighted 
![1CCFFE1E-BAA0-44DE-894D-C3BBD565FC68](https://user-images.githubusercontent.com/97339607/222180817-7f7c854b-829f-4f2c-95f3-365146e94781.jpeg)

**Comment by ismaelAbogabal** [comment]
We start highlight it after jumuaa end

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Ok i will check itIbrahim ZEHHAFFounding CEOhttps://mawaqit.net    On 2 Mar 2023, at 17:08, ismaelAbogabal ***@***.***> wrote:﻿
We start highlight it after jumuaa end
