### ISSUE TITLE
Hide none translated languages (0% translated word) from the language selector screen

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#627]
### Some langauges has zero % translated these languges should be hidden from the language selector menu 
![image](https://user-images.githubusercontent.com/63953869/224141822-23467070-1480-4ffe-9796-ef9f5564ce5e.png)

**Comment by ismaelAbogabal** [comment]
@omar-cherif 
Crowding has a field to disable exporting the non-translated file I enabled it 

![image](https://user-images.githubusercontent.com/63953869/224475233-f174411b-9975-4565-8f1d-0f385998d78b.png)

**Comment by ismaelAbogabal** [comment]
@omar-cherif 
Crowdin configuration has two source branches we need to remove the l10n_main
![image](https://user-images.githubusercontent.com/63953869/224475464-0a0f9df4-6e0a-4826-8e11-0535080a9c0a.png)

**Comment by omar-cherif** [comment]
Excellent @ismaelAbogabal, I did not know that we can only sync the complete translations.

- Yes, please remove the obsolete branch, and re-sync everything again.

@patpatnomi (Patryk) will do the same en the mobile-app
