### ISSUE TITLE
Random wrong iqama countdown

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#631]
![906E27F0-3F21-4DF6-B9B4-67EEDAFD78BE](https://user-images.githubusercontent.com/97339607/224484360-29fbd8c4-98ef-497e-a099-139129d05a5e.jpeg)

sometimes the Iqama countdown is not ok

**Comment by ismaelAbogabal** [comment]
Test cases 

- [ ] adhan voice-enabled/disabled/Bep (should stay at least 2min)
- [ ] after adhan duaa enable/disabled
- [ ] after adhan duaa voice should match the adhan 
- [ ] Duaa between adhan and iqama work when (after adhan enabled & there is enough time until next iqama 30 at least)
- [ ] Iqama countdown enabled/disabled
- [ ] Iqama count can't have more than 30min if the next iqama is more than 30 min that means iqama time started 
- [ ] Iqama screen can be enabled/disabled and should disable all the screens from the iqama count down and forward
- [ ] show black screen during salah time 
- [ ] After salah azkar will be at the end of the list if it's enabled on the server 'Invocations after salat'
