### ISSUE TITLE
Dhul qiada instead of dhul hidjja

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#632]
When I tested eid prayer times, I noted that the month is not right, you can put the date in 20 june for example to test, you have to see Dhul hidjja

**Comment by ismaelAbogabal** [comment]
dhuAlhijjah is translated into Dhu al-Qi\'dah
this issue is a translation issue 

![image](https://user-images.githubusercontent.com/63953869/224557740-62a9cb5e-a9d9-4705-ad91-a27d6b35d0f1.png)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This issue is fixed from crowdin pull request
