### ISSUE TITLE
Highlight the next prayer after iqama 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#650]
Please highlight the next prayer after iqama and not after adhan

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This is the current behaviour I test in the 10 screens 

What is the screen this issue appears on?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The main screen, I had the adhan of isha and immediately, the fajr was highlighted

**Comment by ismaelAbogabal** [comment]
Got you this happen because Ishaa iqama is set to +0  
will handle this case

**Comment by ibrahim-zehhaf-mawaqit** [comment]
thanks, but don't merge plz
I will tag the PRs to merge after my tests
cc @omar-cherif
