### ISSUE TITLE
[URGENT] Somes mosques are not able to display the screen

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#666]
We have 2 mosques ID 14848 and 14746

![image](https://user-images.githubusercontent.com/97339607/227053555-c6135106-4669-472c-aaee-bfc1fee69366.png)

![image](https://user-images.githubusercontent.com/97339607/227053816-b5eadda7-76f6-4e39-ae81-561ecfe28424.png)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This seems as an issue with the UUID Becouse its returning 404 response message 

![image](https://user-images.githubusercontent.com/63953869/227153783-9c949eb0-b23a-4861-97af-94cecbb56eba.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
ok I take the point
