### ISSUE TITLE
[URGENT]The hijri date is not good

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#667]
v1.1.32

For today march 23th It must be 1 ramadan instead of 30 shaban

![13627AA7-30C5-43BD-B44D-F609A6F45CE2](https://user-images.githubusercontent.com/97339607/227110125-01bbd734-66cb-41c6-8bc6-39bd661fc560.jpeg)

The mobile app, the webapp, and tje webview are good

![451290BD-F75B-4AED-ADBE-A1FD1322C748](https://user-images.githubusercontent.com/97339607/227110590-29785597-2ce3-4549-8c74-25b02139133a.jpeg)

**Comment by ismaelAbogabal** [comment]
Because mosques have hijri date adjustment set to -1 

![image](https://user-images.githubusercontent.com/63953869/227150705-e8279a35-dbad-4dd8-af65-089d45d241f7.png)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Wait please I don't agree with this
adjustment is an info sent from the backend by the mosque admin
It should be applied the same way on all the channels
