### ISSUE TITLE
[URGENT] eid is no loger handled 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#684]
eid must be displayed and highlighted 7 days before 

this is a regression 

![E356FF10-A2B4-4A95-B427-4D9810B0990B](https://user-images.githubusercontent.com/97339607/227600789-925b9cb4-4cf7-4abd-9cd5-6910496a5f23.jpeg)

**Comment by ismaelAbogabal** [comment]
This should be fixed on this commit 98eb6a165d31b0fc5bfb93cafe44a2c6cd605364
