### ISSUE TITLE
Much space between the title and the jumua hadith

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#695]
![E165163A-EA17-41C0-B8BB-D25CB960B6D3](https://user-images.githubusercontent.com/97339607/227709236-603b8b2a-0c5f-4e2f-a10c-f600e056600a.jpeg)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This issue happen because there are line breaks (\n) in the first of the hadith this may be because of crowdin This happen in 

- afterSalahHadith
- jumuaaHadith
- afterAdhanHadith

I will fix it from crowdin

**Comment by ismaelAbogabal** [comment]
This issue is fixed and should be closed 
@ibrahim-zehhaf-mawaqit Please check it out
