### ISSUE TITLE
Dua iftar assa'im

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#709]
For Homes, schools..etc NOT mosque
Show dua assa'im and play the dua sound 2 min before adhan al maghrib during ramadan

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit Please test out this

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal 

![IMG_9732](https://user-images.githubusercontent.com/97339607/229831434-702f6001-64df-40cd-af5d-d553620cf8d9.jpeg)

- [ ] Sound is ok but the dua text is not good
- [ ] Sound is enabled for mosque, this is not good

I would like to update the specifications 
- [ ] Show dua for mosques also but without sound
- [ ] Show the dua with prayer times, countdown and current time like the Hadith screen 
- [ ] Show the dua 2 minutes before adan during 90 sec, so the main screen will be restored 30 sec before adan

**Comment by ibrahim-zehhaf-mawaqit** [comment]
these two points are not ok in the last release 1.1.54
- [ ] Sound is ok but the dua text is not good
- [ ] Show the dua 2 minutes before adan during 90 sec, so the main screen will be restored 30 sec before adan

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit This is the current state 
>  Show the dua 2 minutes before Adanduring 90 sec so that the main screen will be restored 30 sec before Adan

The duaa starts 2 minutes before the adhan 
The duaa ends 30 seconds before the adhan 


This should be working 

The Text should be done from crowding
