### ISSUE TITLE
Add announcements screen mode

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#713]
During the onboarding the user can choose even to use the app for prayer times or for announcements only

so after choosing the mosque (only if a mosque is chosen) show an option to select the mode 

the choice must be persisted in the data base

if the user choose announcements mode

The app will display permanently the announcements with prayer times, current time and flash message on the bottom

See this example https://mawaqit.net/fr/messages/id/1

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
1. Will it show the workflows of salah and jumuaa? 
2. Will it show the random hadith 

or just this page from 0 to ever

**Comment by ibrahim-zehhaf-mawaqit** [comment]
No only announcements no other screen

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Times should respect the format 12/24 chosen by the admin user

next prayer should be highlighted

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Add countdown and time like on random Hadith screen 

so no need for time on the bottom
