### ISSUE TITLE
Play adhan for homes

### ISSUE THREAD

**Issue by anouarchattouna** [mawaqit/android-tv-app#718]
It would be great to play adhan in time of prayer (for non mosque) especially for homes.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
This is the case @anouarchattouna

**Comment by anouarchattouna** [comment]
> This is the case @anouarchattouna

was not the case for me. Is there any specific configuration for that?

**Comment by ismaelAbogabal** [comment]
@anouarchattouna I tested adhan's voice in my home 
This is available from the configuration on the mawaqit.net [website](https://mawaqit.net)
![image](https://user-images.githubusercontent.com/63953869/228858273-979ccefa-19e4-4254-b33c-d3e12d0b17fc.png)

If you already enabled it from the configuration and it still not working 
Please let me know

**Comment by anouarchattouna** [comment]
@ismaelAbogabal nothing changed
BTW: I am using other applications in the same android box and I've not facing any sound issues

**Comment by ismaelAbogabal** [comment]
@anouarchattouna 
If possible give me your home id so I can test it from your point of view

**Comment by anouarchattouna** [comment]
15154
