### ISSUE TITLE
Add vertical view 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#733]
Need design 

Some mosques have no choice other to put the tv in vertical, so we need to support this view insh'Allah 

![image](https://user-images.githubusercontent.com/97339607/235622311-2442aec7-8721-4b9d-800d-dd4cf1080d0f.png)

**Comment by omar-cherif** [comment]
Yes @ibrahim-zehhaf-mawaqit You are right, we also did open an inssue in the backend repo regarding that.
But now that the horizontal version is working fine, the UX-UI team incha'Allah will suggest a vertical design as soon as possible.

I'll create the page on Figma for that and ping them.

**Comment by ismaelAbogabal** [comment]
@omar-cherif  @ibrahim-zehhaf-mawaqit 
If you want I can start to work on this issue.

Please provide me with the instruction on how can I see the vertical view on the javascript version of the app.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal Not yes please, this issue need design by the UX/UI team
I suggest your these issues 
https://github.com/mawaqit/android-tv-app/issues/760
https://github.com/mawaqit/android-tv-app/issues/743
https://github.com/mawaqit/android-tv-app/issues/719
https://github.com/mawaqit/android-tv-app/issues/694

**Comment by ismaelAbogabal** [comment]
# Notes from the last meeting 

- [ ] Allow the user to enable/disable the vertical mode in the onboarding and from the app 
- [ ] Auto highlight the mode based on the actual monitor specs 
- [ ] Onboarding layout should be affected by the vertical mode 
- [ ] Home salah items should be affected by vertical mode  
- [ ] bottom salah screen should salah in two lines with the name 
- [ ] Azkar text should fill in 0.7->0.9  of the screen 
- [ ] flash widget should come in two lines

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Here are some feedback 
The force portrait is good 👍 

- [ ] put the same margin left and right 
![IMG_0224](https://github.com/mawaqit/android-tv-app/assets/97339607/902da7b2-bb81-47fb-8c6b-4bee6fbf3b96)

- [ ] increase the message flash text size x2
![IMG_0222](https://github.com/mawaqit/android-tv-app/assets/97339607/967eaa8f-e72c-4e7a-8d46-ef7c03bd3b54)


- [ ] Increase the prayer times text size to be equal to shuruq and jumua time
- [ ] Increase the iqama text size x2, but should be smaller than prayer times
- [ ] Increase the prayer names text size to be same as shuruq and jumua name 
- [ ] increase the qr code size x2
- [ ] Increase the mosque title to x2

![IMG_0223](https://github.com/mawaqit/android-tv-app/assets/97339607/af4f633c-8dc6-425a-94fd-9f6ff46f13df)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
We may take this in two lines. 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/c9afc093-b02a-4212-bdfa-87ee620baba1)
