### ISSUE TITLE
Multible flavors 

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#736]
We have two output types of the app one with 
- lean back feature enabled (com.kanout.mawaqit)
- lean back feature disabled (com.mawaqit.androidtv)

We need to have two build flavours and two code magic CD one for each application

**Comment by omar-cherif** [comment]
@ismaelAbogabal for the 2nd flavor without the Leanback, please don't just use the false value. Remove the line completely (because on some boxes the app is still not installable from the Play store). Example: Xiaomi Mi Box S.
