### ISSUE TITLE
Create a setting screen

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#741]
Move all user preferences into single screen 

So user can edit these values easily 
instead of lazy putting it in the drawer menu

**Comment by ismaelAbogabal** [comment]
@omar-cherif 
I created the settings screen 
Could you please provide me with an animation that can fit in this particular UI 

![image](https://user-images.githubusercontent.com/63953869/230663324-eaca4c41-655b-4ad0-abaa-575bbd45a993.png)

**Comment by omar-cherif** [comment]
@ismaelAbogabal Baraka'Allahu fik for this great alternative.

Could you please provide some additional screenshots (or a video recording so we can better understand the user flow to arrive to that screen?

Chokran

**Comment by ismaelAbogabal** [comment]
[untitled.webm](https://user-images.githubusercontent.com/63953869/231267875-381c8cc1-18e1-4ebb-878c-bb15b6867a0f.webm)
