### ISSUE TITLE
Add prayer times, countdown and current time on athkar after salat screen 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#746]
![IMG_9733](https://user-images.githubusercontent.com/97339607/229836282-cd4fbfc0-8ee7-4da1-b9bf-74f4096af230.jpeg)

Like the Hadith screen

**Comment by ismaelAbogabal** [comment]
Shall I add it to the screens that don't have it like 

- [ ] after adhan duaa
- [ ] count down
- [ ] Iqama 
- [ ] Duaa remainder between adhan and iqama
- [ ] after salah azkar
- [ ] Breakfast duaa
- [ ] Jumuaa hadith
