### ISSUE TITLE
Add Norwegian language 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#760]
We have 3 mosques in Norway 
The brothers in this country asked me to add there language

**Comment by omar-cherif** [comment]
Yes of course @ibrahim-zehhaf-mawaqit, all translators are welcome to join our team.

But please ask them to apply at: https://volunteer.mawaqit.net so we can add the to the Translation Team incha'Allah.

The Translation Team leader will on-board them and send the the access to Crowdin, then approve (proofread) the translations before going into production.
