### ISSUE TITLE
City name still displayed despite option (Display the city name) is disabled

### ISSUE THREAD

**Issue by Yassine-code** [mawaqit/android-tv-app#770]
City name still displayed despite option (Display the city name) is disabled

![image](https://user-images.githubusercontent.com/63513837/233369445-eea5ad85-2935-41be-b70c-d9f1b221387b.png)
![image-message](https://user-images.githubusercontent.com/63513837/233370542-3728f8f4-4054-417d-80fe-529d29959a4b.jpeg)

mosquee ID with the issue : 15259

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
In the API we got the name field in the 'name - city' format 
we do split to separate the name from the city 

in this case, because we have more than one '-' we can't rely on the split 
So can we modify the API to have the city in a separated field from the name?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal ok so please don't implement this logic, it will be handled from the backend
