### ISSUE TITLE
Shuruk time is not correct at mosque 15415, doesn't update

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#775]
**Describe the bug**
Shuruk time is not correct at mosque 15415 with android TV **1.1.47**/**1.1.54**
Shuruk time must be **6:01** not **6:09**, I have checked the back-end and mobile APP and are both working correctly.

**To Reproduce**
start mawaqit smart TV and use the mosque id 15415

**Additional context**
![shuruk-mobile-15415](https://user-images.githubusercontent.com/9025636/235137232-8f0a486f-53a7-4210-967a-dbd2c5e4c9ca.png)
![shuruk-tv-15415](https://user-images.githubusercontent.com/9025636/235137239-da0999eb-2e74-4374-98a5-2baac5377328.png)

**Comment by Salahaldeen-altous** [comment]
I have now tried to re-import the time for April and it seems to work. but the bug is still there. Now I will monitor if shuruk time will decrease in the next days or stay the same 6:01. 

this bug have been reported in two mosque in turkey which are using android box/TV. with pi no problem.
specially one mosque is using the offline version.

**Comment by Salahaldeen-altous** [comment]
I have tested again, the bug still exists. every day I must import the timetables once and then the shuruk will be updated.
this is an urgent bug for Turkish mosques because they dependent in Shuruk for praying fajir

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@Salahaldeen-altous its ok v1.3.0 available as internal test
Can you test

**Comment by Salahaldeen-altous** [comment]
@ibrahim-zehhaf-mawaqit 
How I can download the new version, from play store or cdn link?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Play store with your internal tester email Salahaldeen.altous@googlemail.com

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Search for MAWAQIT For TV app

**Comment by Salahaldeen-altous** [comment]
@ismaelAbogabal @ibrahim-zehhaf-mawaqit 

I have now tested version 1.3.0, alternating imask and shuruk is working fine, but fajr time is not getting updated (same problem as shuruk before. It shows the Fajr time from the previous 2 days!!)

This was not visible at the first quick test!!

![Screenshot_20230503_051339_MAWAQIT.jpg](https://user-images.githubusercontent.com/9025636/235822116-0f8e3456-6f43-4b8c-8005-cec119845d85.jpg)

![Screenshot_20230503_051244_MAWAQIT.jpg](https://user-images.githubusercontent.com/9025636/235822117-30ff60c8-594c-4e1b-a8f4-ebceddcbc736.jpg)
