### ISSUE TITLE
Show both shuruk and imask time alternatively as hijri/gregorian dates specially in Turkish mosques 

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#776]
**Is your feature request related to a problem? Please describe.**

Fajr athan time is more related to shuruk time than imask time in turkey, we need to show both alternatively the whole day and not only after Fajr time.

**Describe the solution you'd like**
Similar to  hijri/gregorian specially dates

**Describe alternatives you've considered**

**Additional context**
Please check the attached video from the analog prayer time clock.

**Comment by Salahaldeen-altous** [comment]
https://user-images.githubusercontent.com/9025636/235326504-71cd7aab-2e87-434a-9292-315c4c1691c7.mp4

![Screenshot_20230428_145245_Namaz Vaktim.jpg](https://user-images.githubusercontent.com/9025636/235326543-c8064621-bc9a-4891-b32b-2ad159bd15cd.jpg)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal do that only for turkish mosques country code = TR from the info API

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@Salahaldeen-altous its ok v1.3.0 available as internal test
Can you test

**Comment by Salahaldeen-altous** [comment]
> @Salahaldeen-altous its ok v1.3.0 available as internal test
> Can you test

I can only test version 1.2.0 from play store!!

**Comment by ibrahim-zehhaf-mawaqit** [comment]
retry please with your email Salahaldeen.altous@googlemail.com
