### ISSUE TITLE
Remove the api token from the app

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#786]
https://github.com/mawaqit/android-tv-app/blob/cc6f3dbaa62181e9a57e49142288d34e6a3a3557/lib/src/helpers/Api.dart#L15

The project is open source, please remove the token from the source code and put it in en env github var.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal please use code magic variables here 
![image](https://user-images.githubusercontent.com/97339607/236673973-47425cba-907a-44a2-b6ec-53dd4ef20c4a.png)

So you have to change the name of the var

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit  Codemagic updated 
I also downloaded the APK and tested it.

Shall we move the sentry SDK DNS UR

https://github.com/mawaqit/android-tv-app/blob/b9c5a1e8d5e4fcc90f51639605a71748b82593ae/lib/main.dart#L29

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes all secrets must be removed please
