### ISSUE TITLE
Reduce margin for top time and next prayer

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#794]
Align with prayer times

![image](https://user-images.githubusercontent.com/97339607/236878156-f9e5e4ae-6cb0-40cf-a477-4f8076b8c500.png)

**Comment by ismaelAbogabal** [comment]
This is fixed in this commit f1296250625abbfc7f2788587b7a026fe5d8ea1e

I added it to the vertical view pull request because after that the old salah bar will not be used anymore 
so this is fixed once and for all.
