### ISSUE TITLE
New settings screen

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#800]
- [ ] Some texts are not translated

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
All keyword is moved to the intl_en.arb file 
So it needs to be handled from crowdin. 

I will do the Arabic translation as I know Arabic.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit  
I check out the crowdin seems there are an issue with token 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/18ae53d5-58d5-4ad9-bad8-e80914cb279e)
![image](https://github.com/mawaqit/android-tv-app/assets/63953869/ee08235b-f556-4296-9437-02aeb2dc1d93)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes @ismaelAbogabal every time you add new text to the app, translate theme in all the available language with automatique translation (deepl or other tools)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
The translation is only uploaded to crowdin after we merge the code into the main branch.
I will check if there is an option that will trigger the machine translation automatically after the translation is uploaded to the crowdin.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit Crowdin supports building custom workflow. for this specific use case so when we do a pull request the translations will be uploaded into their console then auto-translated. and then the crowdin will create a pull request into our repo.

https://support.crowdin.com/custom-workflows/
