### ISSUE TITLE
Show Time (Digital/Analog) Instead of Complete Black Screen During Salah

### ISSUE THREAD

**Issue by Masum2004** [mawaqit/android-tv-app#814]
**Is your feature request related to a problem? Please describe.**

Some other mosque displays (Not using MAWAQIT) shows the Time or Salah Name during the salah. It will be good to have the option available in MAWAQIT to chose by a toggle buttons within the display config. 

**Describe the solution you'd like**
Digital or Analog clock displayed at the centre of the screen when the display is turned of during salah, so that it doesn’t look like a broken screen.

**Describe alternatives you've considered**
At present the only option is to enable the black screen or not.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Thank you
but we prefer to keep the screen black
