### ISSUE TITLE
Update codemagic

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#829]
- [x] create codemagic.yml and put all the configuration in it
- [x] Add an internal build step to submit the abb file on google play MAWAQIT For TV app
- [x] Add a build step to submit the apk file to s3 here s3://cdn.mawaqit.net/android/apk/

**Comment by ismaelAbogabal** [comment]
For the deployment into AWS 
According to this [Article](https://docs.codemagic.io/yaml-publishing/aws/)
Could you add the 
- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY

**Comment by ismaelAbogabal** [comment]
Also, I would suggest enriching our GitHub releases with the build APKs 

If that is okay We can flow this [article ](https://docs.codemagic.io/yaml-publishing/github-releases/)
Just need the env variable 
- GITHUB_TOKEN

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> For the deployment into AWS According to this [Article](https://docs.codemagic.io/yaml-publishing/aws/) Could you add the
> 
> * AWS_ACCESS_KEY_ID
> * AWS_SECRET_ACCESS_KEY

You have already these credentials sent in discord, you can't add them ?

**Comment by ismaelAbogabal** [comment]
No, I cant edit the credentials on Codemagic.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> * GITHUB_TOKEN

done

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> No, I cant edit the credentials on Codemagic.

done

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> Also, I would suggest enriching our GitHub releases with the build APKs
> 
> If that is okay We can flow this [article ](https://docs.codemagic.io/yaml-publishing/github-releases/) Just need the env variable
> 
> * GITHUB_TOKEN

done
