### ISSUE TITLE
Mosque searching ko

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#836]

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit I tested it and it worked for me.
Maybe it was a server issue. 

Could you provide more context for the issue?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Try to change mosque fro the the settings menu

**Comment by ismaelAbogabal** [comment]
[Record.webm](https://github.com/mawaqit/android-tv-app/assets/63953869/47f92c79-76e7-42bf-b554-f7aede97b25f)

**Comment by ismaelAbogabal** [comment]
[record.webm](https://github.com/mawaqit/android-tv-app/assets/63953869/0b3970a9-964e-4c46-8288-44f9b4557b19)

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit I found out the issue 

This happens because MAWAQIT_API_KEY is not available in the CD context
We need to add it into the add APP into the group 

https://github.com/mawaqit/android-tv-app/blob/9ffb891ee49e5d57507ac9a8e2f3fad71334b05c/codemagic.yaml#L23-L26

for this particular issue, I have written a test file to test whether these keys actually exist 
But also is not added to the CD will add both and create a pull request.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Yes you have to add the group APP
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/dde30b6b-fbc9-44e4-b84a-5c12b9a5d754)
