### ISSUE TITLE
Call life status api

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#852]
Call every 10 mins

POST api/3.0/mosque/{uuid}/androidtv-life-status

{
  "unique_id" : 
  "mac_address" : 
  "box_brand" : 
  "box_model" :
  "android_version" :
  "app_version" :
  "orientation" :
  "other_setting" : 
   ...
}

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal please try catch every info so if it's not available, this will not crash the app

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal the api is live imon staging and production

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit ok data is ready will send it using the api.

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit There is an internal server error 

![image](https://github.com/mawaqit/android-tv-app/assets/63953869/aba9705c-2f26-48dc-b127-0d46d9975527)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
device-id instead of unique_id, that what you suggest and I found it a good idea
