### ISSUE TITLE
Integrate random hadith in offline mode 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#856]
Download the hadith xml files at the mosque sync step depending of the language of hadith in info data

Files are available on this url pattern https://[env-host]/static/xml/ahadith/[lang].xml
env-host = mawaqit.net or staging.mawaqit.net depending the env chosen in the app
lang = ar, tr, ar-tr ...etc to pick from /info data

For example 
if language = ar than download the ar.xml file
if language = tr-ar than download the ar.xml and tr.xml files

If the box is offline get a random hadith from the downloaded files instead of the hadith api
if 2 language are chosen than random from the 2 files

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit Incase of user is online. why use the API? we can use that to reduce the API calls.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I prefere use the api to get the last updated ahadith, don't worry about the server load, this api is cached

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The screen is blank for a few seconds before the hadith is displayed

**Comment by ismaelAbogabal** [comment]
We are relying on the cloud flare cache. May this happen because we cleared out the Cloudflare cache? But now its working fine from my side. 

[untitled.webm](https://github.com/mawaqit/android-tv-app/assets/63953869/96bda518-23d0-43aa-a0d4-b60c83165ecb)
 Please double-check if it's good now.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal your test is not ok, you are testing with wifi connection and you test the screen from the debug menu.
Please test on a real device following these steps 

1. Install and setup the production version v1.6.1
2. update to the internal test version 1.7.0
3. Launch the app
4. Stop WIFI
5. Kill the app 
6. Open it again
7. Wait for the hadith
