### ISSUE TITLE
Jumua live streaming must be displayed on the main scree for homes, schools...etc

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#880]
Except for mosques, the streaming should be displayed in secondary mode only

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 

I think this is the current logic. 

The jumuaa  will be skipped only under 3 conditions 
- There are no stream URL 
- There are no live on the channel 
- Mosque and primary screen mode is active 

Unless We will show the dhikr or black screen.
