### ISSUE TITLE
 screen is a TV 

### ISSUE THREAD

**Issue by Mario526bedf** [mawaqit/android-tv-app#883]
![IMG_20230827_150909](https://github.com/mawaqit/android-tv-app/assets/135725897/0ab8df42-efd5-4b46-8065-d1dc4cd25bd8)
In this mode the screen does not turn off.  Please fix this problem

**Comment by ismaelAbogabal** [comment]
HI @Mario526bedf 
Thanks for the contribution. 

The logic is 
- The screen should be always on and keep working whether this option is enabled or not

So what is your observation? 
Is the screen turning off when this option is disabled?
