### ISSUE TITLE
Wrong direction of scrolling Arabic bottom message

### ISSUE THREAD

**Issue by alias2006** [mawaqit/android-tv-app#897]
**Describe the bug**
The bottom message in Arabic is scrolled from right to left.

**To Reproduce**
1. Arabic interface
2. Enter any Arabic bottom message in config
3. See error in vertical view

**Expected behavior**
The bottom message in Arabic must be scrolled from
 left to right in vertical view

**Android TV/Box (please complete the following information):**
 - Device: Samsung Galaxy A50
 - OS: Android 11
 - Version [e.g. 1.7.0]
- Build [e.g. 254]
-

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Please check again the issue is solved, be sure that the configuration of your message is good "Right To Left"
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/85b031dc-30bc-4825-a82c-b00eb21c3243)
