### ISSUE TITLE
Enable select the hadith Language based on the app langauge (overwrite the backend chosen value)

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#898]
We are planning to support multi TV in one mosque and each TV will support different Language (e.g Turkey).

currently the Hadith are supported offline and it would be nice if we can add support to choose the hadith language which will enable each TV to show the Hadith language which compatible with the app language

For example we have 3 TV in one mosque and each of these TV have different Langauges (TR, EN and AR).
it would be very nice that the TR-TV shows the hadith in Turkish and the EN-TV show the hadith in English and the AR-TV shows the hadith in Arabic.

**Comment by YassinNouh21** [comment]
**Questions related to the problem**
- Each box has its api or the mosque itself has the api?
- If the box can support multiple screens?
- Is this feature primarily dependent on the backend or the Flutter side?

**Comment by ghassenbenzahra123** [comment]
**Implementation suggestions** 

- On the user onboarding screens, he can choose other languages that he might use for the hadiths in the future to directly fetch them and save them for the offline mode.

- It will have an option in the setting beneath the change mosque. Change the default option that is fetched from the API with the desired language and save it locally. If in case that he wants to override this behavior it has flag in this page to switch from local mode into api mode.

**Comment by YassinNouh21** [comment]
### Implementation suggestions
#### Language Customization Option
- **Location**: This feature will be integrated under the 'Change Mosque' settings section.
- **Functionality**: The primary function will be to substitute the default language option, currently retrieved from the API, with a user-selected language preference.
- **Local Storage**: The selected language setting will be stored locally to ensure persistent user customization.

#### Toggle Feature for API-Local Mode Transition
- **Purpose**: To provide users with the flexibility to choose between the locally stored language setting and the default API-driven setting.
- **Implementation**: A toggle switch will be added in the same settings section, enabling users to seamlessly switch between the 'Local Mode' and 'API Mode'.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> * Each box has its api or the mosque itself has the api?

The question  is not clear for me, the box is independent and the api is stateless 
Each box has its proper settings but the result of the api is the same for all

> * If the box can support multiple screens?

Yes but need an hdmi splitter 
> * Is this feature primarily dependent on the backend or the Flutter side?

The hadith language is chosen by the user on the backend side so it can be different to the front language 

![IMG_1586](https://github.com/mawaqit/android-tv-app/assets/97339607/37f021fc-37a9-469c-9a18-971998d20437)
![IMG_1587](https://github.com/mawaqit/android-tv-app/assets/97339607/596d9514-d520-4e19-92ac-d4cbe46c356d)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> **Implementation suggestions**
> 
> * On the user onboarding screens, he can choose other languages that he might use for the hadiths in the future to directly fetch them and save them for the offline mode.

Hum good question for the offline but I don't agree with doing it on the on boarding, I suggest to ask the user to connect to the Internet if he want to change the language of the hadith from the settings, so we can download xml files for the new language and delete the old one

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> ### Implementation suggestions
> #### Language Customization Option
> * **Location**: This feature will be integrated under the 'Change Mosque' settings section.
> * **Functionality**: The primary function will be to substitute the default language option, currently retrieved from the API, with a user-selected language preference.
> * **Local Storage**: The selected language setting will be stored locally to ensure persistent user customization.
> 
> #### Toggle Feature for API-Local Mode Transition
> * **Purpose**: To provide users with the flexibility to choose between the locally stored language setting and the default API-driven setting.
> * **Implementation**: A toggle switch will be added in the same settings section, enabling users to seamlessly switch between the 'Local Mode' and 'API Mode'.

I think we don't need a toggle button just a select list with all the languages options (same as the backend list) by default nothing is selected so the backend value is used
