### ISSUE TITLE
Update UI and Logic for Turky (Imsak and Sabah)

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#900]
https://www.canva.com/design/DAFuog054Yw/xoDLEud1A3JYaZ6TzDaqww/edit

- [x] Update UI to have 6 squares of salat times
- [x] Update the adhan and iqama logic to be related to Sabah
- [x] Will use a new version of api /api/3.1
- [x] For Turkey only (based on calendar columns 7)

![image](https://github.com/mawaqit/android-tv-app/assets/97339607/6a12344d-f0e2-4f3e-89bc-3ddaecc70342)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal the api v3.1 is available on staging
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/2d1f6572-d6a3-4bb3-9731-e80003610f9c)

In this new api I removed these indexes
```
'hijriAdjustment' => please pick it from the new api http://swagger.mawaqit.net:83/#/default/get_mosque__uuid__hijri_date
'hijriDateForceTo30' => please pick it from the new api http://swagger.mawaqit.net:83/#/default/get_mosque__uuid__hijri_date
'times' => obsolete
'shuruq' => obsolete,
```

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit 
The mosque search API is failing on the staging API endpoint (return 500 server error exception)
[Request](https://staging.mawaqit.net/api/2.0/mosque/search?word=cami)

Please give me mosque name, id or UUID to test with

**Comment by ibrahim-zehhaf-mawaqit** [comment]
You can get a uuid by calling the get by id api
id 1
I will fix the search api insh'Allah

**Comment by ismaelAbogabal** [comment]
@ibrahim-zehhaf-mawaqit I am getting 403 Forbidden resources on all the requests to the staging subdomain 

Is there are different access tokens for the stagging API? 

The access token is working fine on the regular domain mawaqit.net

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Which token you are using ?
Try with this one 86ed48fd-691e-4370-a9bf-ae74f788ed54

**Comment by ismaelAbogabal** [comment]
Yes, it is working it was an issue with my postman.
