### ISSUE TITLE
Cache directory overloaded

### ISSUE THREAD

**Issue by ismaelAbogabal** [mawaqit/android-tv-app#903]
[Sentry issue](https://mawaqit-01.sentry.io/issues/4116499501/)

The most occurring issue is that the case directory is overloaded we can deal with it.  by 
- moving the images into the user data cache 
- OR build a cache manager that is responsible for cleaning up the cache dir

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Add more sentry log to have more information and be able to anlyze efficiently
