### ISSUE TITLE
Weather icon is sometimes wrong

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#908]
In this example it shows the sun while it's isha time 

please take the icon from the api

![Image](https://github.com/mawaqit/android-tv-app/assets/97339607/767cfb6d-5104-4987-add2-f8e5662a7033)

![IMG_1146](https://github.com/mawaqit/android-tv-app/assets/97339607/60e93c8d-27c8-41d8-a618-0a9fc6272197)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
It is always wrong
In the night we must have moon icon and not sun

![IMG_1316](https://github.com/mawaqit/android-tv-app/assets/97339607/96c945c6-924e-4aab-93d7-9c64f2473629)

![IMG_1315](https://github.com/mawaqit/android-tv-app/assets/97339607/f9d083b6-b41c-4f87-95d7-cb99b9a91390)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Closed ? I don't see a PR

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal ?

**Comment by ibrahim-zehhaf-mawaqit** [comment]
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/19e020ab-ca1b-4ef1-a6bb-bd1ee88f5286)

**Comment by ismaelAbogabal** [comment]
Metting note
Convert 'sunny' to 'clear' in the nighttime.
