### ISSUE TITLE
Request for Latest MAWAQIT TV APK 

### ISSUE THREAD

**Issue by khalilyamoun** [mawaqit/android-tv-app#910]
Assalami Alaykum,

I hope this message finds you well. Our mosque have been using MAWAQIT for a while now and find it to be a valuable tool for prayer times and notification.

I noticed that the Google Play version is stuck at 1.6.1-tv, and I was wondering where I can find the APK file for the latest releases (1.7.0..1.7.1). Additionally, is it recommended to compile and generate the APK by ourselves? 

Jazakom Allah.

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salam alaykum
We have the latest version on google play 1.8.2, please check again
You can also download our last apk here https://get.mawaqit.net/apk/tv
