### ISSUE TITLE
The shuruk time is now equals the sabah time which is not correct.
V1.7.1-260

The shuruk time must be taken from the time table.

Also the sabah translation is missing in arabic

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#914]
![Screenshot_20231001_123055_MAWAQIT.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/ce53a699-2ff5-41fe-b66b-60f857337440)

![Screenshot_20231001_123429_MAWAQIT.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/9672d668-9c74-4e41-aef2-de4ecb4c2be7)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@ismaelAbogabal new P0 issue

**Comment by Salahaldeen-altous** [comment]
After talking to to one Imam here, he asked me for a second version when Iqama is disabled. Now we need two option if possible.
1. When Iqama is disabled (Imask, shuruk, Duhr, Asr, Maghrib, Isha) 
2. When Iqama is enabled (Imask, Sabah, Duhr, Asr, Maghrib, Isha) 

![image](https://github.com/mawaqit/android-tv-app/assets/9025636/8b0487ed-496d-4336-8c16-a22f035130de)

I know for us, I prefer the second one but many mosques will disable the Iqama system.
I am not sure if we should wait for further feedback or implement both version!!

@ibrahim-zehhaf-mawaqit @ismaelAbogabal: if this is something simple we can try it, I know the symmetry looks not good because we will have two double info for Shuruk in the first version (one possible option is to switch sabah and Shuruk when Iqama is disabled)--> if we can do this, then we have covered every thing.

**Comment by Salahaldeen-altous** [comment]
When iqama is disabled, Imask box must be also resized as all other boxes, in announcements window it works fine!

[Screenshot_20231003_103310_MAWAQIT.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/55838a44-2fa7-4d67-87a1-59c6b89bb67d)

![Screenshot_20231003_103359_MAWAQIT.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/b26d77c9-1b11-4c95-bc27-0b36806fdf70)
