### ISSUE TITLE
[Action Needed] Updates to Google TV App Icon Requirements

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#942]
Starting Nov 9th, 2023 Google TV will require developers to provide a square app icon asset as part of the submitted TV app package in addition to the existing banner asset. The provided square app icon asset will be surfaced in circular format on the For You tab in the user’s Your Apps row and will be the primary asset users see when they launch your app. Please refer to the [TV App Icon Guidelines](https://notifications.google.com/g/p/ANiao5oG9r2kOroZB2jb5M9wP9jpKKqn1j3QSDRcmo3M0WVT3cyDY22LlnhlKRL9fYMebP-CjUBkfMgBulX_vhhRcbmHbwQ9dqLdn0uxDSjyvxX3EbkzVeDc4PbFK14Ka_mlJG7MFTQRvLDV_MlLhYJAM7J80xZaPtiLggqq39HUyQnlNzieTLlyBBZSlVQRcWVh2xEaevsJQA7DaQ9lnGh13vIQik4tWbtZVHNDNyLUOW3ulBfFciqu6BRE1eTBtoUgDxKNANG_a2k95uleyMyfpsQ6kYwYc86NJ6BQjPyQh8ZBgv7UUvu-aw) for more guidance on creating app icons for your TV app.

FAQs

What do I need to do?
Ensure that you’ve submitted an updated APK which includes the square app icon assets as defined in the [TV App Icon Guidelines](https://notifications.google.com/g/p/ANiao5qX-4iO0mwdUS7gOCiXSN6X9gBN3p60ClXoVXmiMJIdkTTYnfDoiqOw9_KVyR8tdH3_7Jl7BdV___WrYAvcUHwjR5DUqyi3dArjWBjt9TjSJG5bEd6ouBtMwF6BJhYrMAatB6cd7CC_F2qKu3-xA-EY19wP230CvHCmIiW6mtP91R5lsh5IZOLP7rT1EwwaaCHCG-v--2O4oP2X8vqrU2LMcxKAWO8ZtZVQ71kDzbhFTTQ1D4k3oESRtKg03tt_nsYxd2iw6hyRo54b_icXSzs6Dav_Bm19dNI30bPdX-JijSi0_L9KUA) by Nov 9th, 2023.

What happens if I do not provide a square icon by Nov 9th, 2023?
If your app is already installed on a user’s device or a new user installs your app but there is no launcher icon asset provided, users will see the below Android default app icon.

Default Android App Icon

What devices will be impacted?
This update will apply to all existing (in-field) and new Google TV devices.

Do I still need to provide the 320x180-pixel app banner asset that exists today?
Yes. The rectangular banner asset will still be displayed throughout other areas of the UI so please ensure to include both the square and rectangular assets in your submission.

**Comment by YassinNouh21** [comment]
Based on the [Android Style](https://developer.android.com/design/ui/tv/guides/system/tv-app-icon-guidelines) these are some notes on our case [Doc](https://docs.google.com/document/d/1MNlhHYuT_1XJAzkjMnP7TzCXN1dhJLAym2ElmiWX3Yw/edit). 
I also created drafted figma file for trying to clone the design [Figma](https://www.figma.com/file/sWHiJ2UHfoJK0qWKPQkthN/%5BMAWAQIT%5D-TV-App-Icon-%26-Banner?type=design&node-id=6%3A9937&mode=design&t=E38c6nTBuKnna5SS-1)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The home icon is not ok, the logo is very small and the background color is not good
I suggest to keep only the logo and change the background colo

![Image](https://github.com/mawaqit/android-tv-app/assets/97339607/750b2054-0786-4b37-9e9a-9ada50f7a7e4)

**Comment by YassinNouh21** [comment]
> @YassinNouh21 I don't see the banner picture you used on figma
> 
> ![Image](https://private-user-images.githubusercontent.com/97339607/291906761-65411f91-04b2-4ed8-b008-cd18e22046e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxODcyNDAsIm5iZiI6MTcwMzE4Njk0MCwicGF0aCI6Ii85NzMzOTYwNy8yOTE5MDY3NjEtNjU0MTFmOTEtMDRiMi00ZWQ4LWIwMDgtY2QxOGUyMjA0NmUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDE5MjkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMDVlZTYyZmUyNDRiZjUzMDExNzAyOGE3MjU3MTc5N2E0MzdlNmNjZTU4NTgxNmIwNTkzYmI2ZGI4MThmYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hyTs2bHju4YBsGfwiGLbFwWxVamiFkb_xhKs8eF44-c)

I followed the design provided by the UI/UX team https://www.figma.com/file/9vwJRWAl9KfSGXzHoimp6x/Products?type=design&node-id=705-10381&mode=design&t=MKELZOj8oS7ILGCh-0
