### ISSUE TITLE
Add option to on/off the TV 

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#943]
- [x] Send a signal to power on or off (turn in standby mode) the tv x min before adhan and x min after
- [x] This option must be added  in the settings
- [x] The option should be (disabled or x min), by default it's disabled and set both to 10 min
- [x] If the app is installed on a box, the signal is sent to the TV from the box
- [x] If the app is installed on a TV the signal is sent from the TV itself

**Comment by YassinNouh21** [comment]
https://developer.android.com/training/tv/start/hardware#hardware-permissions

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@mawaqit/android I put this issue in kiosk mode milestone
