### ISSUE TITLE
Random hadiths are not displayed if the option "Disable hadith between 2 prayers" is enabled

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#944]
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/a4d7f0ed-6563-44ef-b5ff-054be9f92850)

I tested between maghreb and isha, the hadith was not displayed

**Comment by YassinNouh21** [comment]
I found that the original implementation of [`isDisableHadithBetweenSalah`](https://github.com/mawaqit/android-tv-app/blob/c01f33e501ea42750446dee90e3d8cc77621a3a0/lib/src/services/mixins/mosque_helpers_mixins.dart#L33) only considered a single period for disabling the Hadith feature
