### ISSUE TITLE
KIOSK mode

### ISSUE THREAD

**Issue by ibrahim-zehhaf-mawaqit** [mawaqit/android-tv-app#945]
- [x]  The app become the only think we can see
- [x]  The app has root permissions
- [x]  The app starts at boot
- [ ]  Update OTA for the OS and the app
- [x]  Update the app onboarding
  - [x]  Select the language (ok)
  - [x]  Set WIFI
  - [x]  Select the mosque
  - [x]  Set the timezone from the mosque infos `"timezone": "Europe/Paris",`
  - [x]  Add WIFI and Timezone select in the parameters menu

**Comment by ghassenbenzahra123** [comment]
@ibrahim-zehhaf-mawaqit  This sub-issue (Add option check for update in the parameters) is handled in this PR #936
