### ISSUE TITLE
Display prayer times in message screen is not working in the android-TV (is always enabled and cannotbe disabled)!! In the web Interface this feature is working fine

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#958]
![Screenshot_20231202_081008_Samsung Internet.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/fb945296-46b3-466e-8bd4-59e67481649b)

![Screenshot_20231202_081259_Samsung Internet.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/9dedde9b-86c0-47bc-8ecd-3f7b769c1cc0)

In the android-TV, this feature is always ON.

![20231201_120516.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/f6740f19-5eda-41e5-8a18-3c7f3c2b79d7)

**Comment by Salahaldeen-altous** [comment]
Must be like this when disabled 
![Screenshot_20231202_082033_Samsung Internet.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/599a37f9-8376-41d4-b58e-8339ef0ab9c9)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@mawaqit/android-tv if showPrayerTimesOnMessageScreen in /config api is false so don't show the prayer times

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Needs backend update 
The option showPrayerTimesOnMessageScreen will be sent in the api /config
PR ready to merge here https://github.com/mawaqit/backend/pull/633/files
