### ISSUE TITLE
Gray Screen on portrait mode

### ISSUE THREAD

**Issue by yasserbenaioua** [mawaqit/android-tv-app#961]
**Describe the bug**
Gray Screen on portrait mode

**To Reproduce**
1. From settings change the orientation to portrait mode
2. Exit the app and reenter again
3. You'll see a gray screen

**Expected behavior**
See the main screen.

**Screenshots**
Check the video via this link: https://drive.google.com/file/d/1NNjFqpUHYV-IaIJuWXYM2g5idFxaLDZ0/view
 
**Android TV/Box (please complete the following information):**
- Device: Android TV
- OS: Android 9
- Version: 1.8.1
- Build: 272

**Comment by ibrahim-zehhaf-mawaqit** [comment]
fixed in the last release
