### ISSUE TITLE
Images in announcement mode is not showing the image correctly, it shows one more transparency layer

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#964]
**To Reproduce**
1. Use mosque ID 17098
2. Switch to announcement mode
3. Exit the app and reopen it again 

I have test with app v1.8.1-272 on both onvo TV and mawaqit box with the same behavior ![20231201_121448.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/265426f0-625d-44d5-826d-4b64e6dc1f24)

![20231201_091117.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/b4606bde-9bef-4a81-8990-fd7fda997d3e)

![20231201_091101.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/980f812e-bff6-4e67-86aa-27366870f0aa)

![20231201_091102.jpg](https://github.com/mawaqit/android-tv-app/assets/9025636/60abbe38-04dd-49ab-823a-e2a0ed45bc11)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@Salahaldeen-altous please tel me if this issue is still relevant, you can test on the version 1.9.3
