### ISSUE TITLE
The screen stuck on “الاذان” 

### ISSUE THREAD

**Issue by FirasTelmoudi** [mawaqit/android-tv-app#970]
**Describe the bug**
The screen stuck on “الاذان” flashing until we have to close the app and open it again

**To Reproduce**
Stuck after the Athan goes on
I noticed it happens after the Fajr Athan (call for prayer) on Tuesday and Thursday and maybe some other times too

**Expected behavior**
The screen should display the remaining time for Iqama

**Android TV/Box (please complete the following information):**
 - Device: [Sonyu Smart TV]
 - OS: [Android 11]
 - Version [1.8.1]
- Build [272]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
The app stucks sometimes on other screens like the dua after adhan screen 
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/3553414e-43f1-4822-a33d-a94144de7aaf)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
@FirasTelmoudi can you test this apk https://cdn.mawaqit.net/android/tv/apk/MAWAQIT-For-TV-v1.9.0-282.apk

**Comment by FirasTelmoudi** [comment]
I'll install it from scratch just in case
Besides i tried to disabled the Bip sound when the Adhan notification goes on
I saw this #1015 maybe the Bip is causing it
كان الله في عونكم وبارك الله فيك وفي ذريتك، امين

**Comment by FirasTelmoudi** [comment]
> @FirasTelmoudi can you test this apk https://cdn.mawaqit.net/android/tv/apk/MAWAQIT-For-TV-v1.9.0-282.apk

الحمد لله
So far so good
I think this build fixes the freeze issues
- [ ] If you please consider fixing the News Ticker
![image](https://github.com/mawaqit/android-tv-app/assets/29250587/eb2cf761-5484-4e59-8697-e0ca8eeeefa5)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
> > @FirasTelmoudi can you test this apk https://cdn.mawaqit.net/android/tv/apk/MAWAQIT-For-TV-v1.9.0-282.apk
> 
> الحمد لله So far so good I think this build fixes the freeze issues
> 
> * [ ]  If you please consider fixing the News Ticker
>   ![image](https://private-user-images.githubusercontent.com/29250587/303849931-eb2cf761-5484-4e59-8697-e0ca8eeeefa5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODE1MjgsIm5iZiI6MTcwNzU4MTIyOCwicGF0aCI6Ii8yOTI1MDU4Ny8zMDM4NDk5MzEtZWIyY2Y3NjEtNTQ4NC00ZTU5LTg2OTctZTBjYThlZWVlZmE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxNjA3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmZmOTE2M2ZkNTY2Y2EwMDk5Mzk4OGNlMzJkMzU3ZWY0NmFlZGZjNDM4ZWZjMGRjOTJlMjhkZDk0ZGRjMTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DpJc0pgN-hHCorCGH4zbrOQVt-gjcfIn2ZAlCpv6ZVc)

We think it's related to your TV, we are not able to reproduce, all our test devices shows the flash message.
And from thousands of mosque you are the only one reporting this issue.
It will be hard to debug it, but we keep it until we find a solution to reproduce

**Comment by FirasTelmoudi** [comment]
> > > @FirasTelmoudi can you test this apk https://cdn.mawaqit.net/android/tv/apk/MAWAQIT-For-TV-v1.9.0-282.apk
> 
> > 
> 
> > الحمد لله So far so good I think this build fixes the freeze issues
> 
> > 
> 
> > * [ ]  If you please consider fixing the News Ticker
> 
> >   ![image](https://private-user-images.githubusercontent.com/29250587/303849931-eb2cf761-5484-4e59-8697-e0ca8eeeefa5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODE1MjgsIm5iZiI6MTcwNzU4MTIyOCwicGF0aCI6Ii8yOTI1MDU4Ny8zMDM4NDk5MzEtZWIyY2Y3NjEtNTQ4NC00ZTU5LTg2OTctZTBjYThlZWVlZmE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxNjA3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmZmOTE2M2ZkNTY2Y2EwMDk5Mzk4OGNlMzJkMzU3ZWY0NmFlZGZjNDM4ZWZjMGRjOTJlMjhkZDk0ZGRjMTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DpJc0pgN-hHCorCGH4zbrOQVt-gjcfIn2ZAlCpv6ZVc)
> 
> 
> 
> We think it's related to your TV, we are not able to reproduce, all our test devices shows the flash message.
> 
> And from thousands of mosque you are the only one reporting this issue.
> 
> It will be hard to debug it, but we keep it until we find a solution to reproduce

The thing is it does work on the old mode though 
And sometime last week in the new mode (for a day or two)
Which is weird
I hope you can find the issue and i'm willing to test it on 4 multiple mosques 
May Allah give you the strength

**Comment by FirasTelmoudi** [comment]
> > > @FirasTelmoudi can you test this apk https://cdn.mawaqit.net/android/tv/apk/MAWAQIT-For-TV-v1.9.0-282.apk
> 
> > 
> 
> > الحمد لله So far so good I think this build fixes the freeze issues
> 
> > 
> 
> > * [ ]  If you please consider fixing the News Ticker
> 
> >   ![image](https://private-user-images.githubusercontent.com/29250587/303849931-eb2cf761-5484-4e59-8697-e0ca8eeeefa5.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODE1MjgsIm5iZiI6MTcwNzU4MTIyOCwicGF0aCI6Ii8yOTI1MDU4Ny8zMDM4NDk5MzEtZWIyY2Y3NjEtNTQ4NC00ZTU5LTg2OTctZTBjYThlZWVlZmE1LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxNjA3MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NmZmOTE2M2ZkNTY2Y2EwMDk5Mzk4OGNlMzJkMzU3ZWY0NmFlZGZjNDM4ZWZjMGRjOTJlMjhkZDk0ZGRjMTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DpJc0pgN-hHCorCGH4zbrOQVt-gjcfIn2ZAlCpv6ZVc)
> 
> 
> 
> We think it's related to your TV, we are not able to reproduce, all our test devices shows the flash message.
> 
> And from thousands of mosque you are the only one reporting this issue.
> 
> It will be hard to debug it, but we keep it until we find a solution to reproduce

I found the issue is when i put the flash message ends the same day i put it on
Like when i submit a flash message for this hadith

عن أبي هريرة ‏أنّ رسول اللّه صلّى اللّه عليهِ وسلّم ‏ذكر يوم الجمعة فقال فِيهِ سَاعَة لَا يُوَافِقُهَا عَبْد مُسْلِمٌ وَهُوَ يُصَلِّي يَسْأَل اللَّهَ شَيْئًا إِلَّا أَعْطَاهُ إِيَّاهُ؛ صحيح مسلم 1398

Starts at 16/02/2024 and ends the same day the text doesn't appear scrolling but when i put it starts at 16/02/2024 and ends on 17/02/2024 it appears normal

I hope you can look into it brother

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Got it thanks
