### ISSUE TITLE
The announcement ticker

### ISSUE THREAD

**Issue by FirasTelmoudi** [mawaqit/android-tv-app#972]
**Describe the bug**
The text in the announcement ticker does not appear

**To Reproduce**
1. Make a flash announcement 
2. Check the TV announcement ticker (below the prayer times)
3. The black announcement appears but no text scrolling in it

**Expected behavior**
There should be a text in the TV

**Screenshots**

**Android TV/Box (please complete the following information):**
 - Device: [Android TV box x96 Mate & Sonyu Smart TV]
 - OS: [Android 11]
 - Version [1.8.1]
- Build [272]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
This issue is always relevant ?

**Comment by FirasTelmoudi** [comment]
> This issue is always relevant ?

Yes, when i annonces a flash message that ends the same day of putting it up
A work around that i'm using is putting a flash message ends tomorrow and i manually disable it at the end of the day

**Comment by ibrahim-zehhaf-mawaqit** [comment]
ok thanks this issue is related to this one https://github.com/mawaqit/android-tv-app/issues/1036 which is in our todo list
