### ISSUE TITLE
Durée du compte à rebours configurable

### ISSUE THREAD

**Issue by g360230** [mawaqit/android-tv-app#978]
Salamou 3alykom wara7matou allah 

Dans notre cas/pays (Tunisie), le délai entre adhan et iqama est trop long pour Sobeh (30 min) et dhoher (plus que 30 min)
Pouvez-vous rendre la durée du compte à rebours configurable
À mon avis afficher un compte à rebours pour 30 min ce n'est pas utile
Je propose d'ajouter un champ dans l'interface de configuration pour gérer la période d'affichage du compte à rebours

baraka allahou fikom

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Le compte à rebours est déjà configurable, c'est le temps d'attente entre adhan et iqama
![image](https://github.com/mawaqit/android-tv-app/assets/97339607/b0855a3f-2eed-4927-a865-86d526b81e89)

**Comment by g360230** [comment]
Wa3laykom Salam

merci pour ta réponse 
Si on active le compte à rebours avec cette option ça va être appliqué sur tout la période entre adhen et ikama 
Par exemple 
- Temps entre adhen et ikama = 30 minutes 
- Ce que vous proposez donne un compte à rebours pendant les 30 minutes 
- Ce que nous cherchons c’est d’avoir un compte à rebours que sur une durée limitée (5 minutes par exemple ) et d’afficher des ahadith sur l’autre période 

c’est bc plus utile à mon avis (plus de hasanet)

Baraka allahou fikom

**Comment by ghadesmh** [comment]
Assalamou alaykoum,
![Screenshot_2024-02-19-13-49-40-275_com mawaqit androidtv](https://github.com/mawaqit/android-tv-app/assets/159727929/100be3df-225b-44bf-83d0-2bf7f153a0ad)
Qu'est-ce que vous pensez lorsqu'on fixe la prière de Dhohr avant 25 minutes d'el Asr dans notre pays (Sauf si mawaqit n'est pas international et juste pour la France).
