### ISSUE TITLE
تحديد وقت الصلاة في شهر رمضان 

### ISSUE THREAD

**Issue by g360230** [mawaqit/android-tv-app#980]
السلام عليكم ورحمة الله وبركاته 

بارك الله فيكم على هذا العمل الجبار 

عندي اقتراح 
بعض المساجد تعتمد وقت خاص في شهر رمضان
مثل : 
- تقليص وقت الانتضار بين الصلاة المغرب و الإقامة 
- اعتماد وقت واحد لإقامة صلاة العشاء طوال الشهر 

هل يمكن إضافة هذه البرمجة في الإعدادات 

بارك الله فيكم

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salam alaykum brother, thanks for the suggestion
Both of your requests are possible on our admin console
You can adjust the waiting time and fix the isha time
