### ISSUE TITLE
Mawqit for TV take the TV Language as the app language by default

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#984]
Onvo TV have one customized FW where the mawaqit app is by default installed.
after you select the TV language, then timezone and then set the WiFi, the mawaqit lanucher started automatically and ask again about the language. 

I prefer to take the TV language or Android box language by default and later you can change it in the setting.
if we implement this, on step will be saved.

![WhatsApp Image 2024-01-03 at 10 26 38(3)](https://github.com/mawaqit/android-tv-app/assets/9025636/b30ae4f5-878c-42f4-8899-4ef51a750688)

![WhatsApp Image 2024-01-03 at 10 26 38(2)](https://github.com/mawaqit/android-tv-app/assets/9025636/44ad4dcd-2ab1-4655-a80e-32c454bf6ee4)

![WhatsApp Image 2024-01-03 at 10 26 38(1)](https://github.com/mawaqit/android-tv-app/assets/9025636/83a24839-d920-47d6-af28-9123e881ecfd)

![WhatsApp Image 2024-01-03 at 10 26 38](https://github.com/mawaqit/android-tv-app/assets/9025636/2131593f-66a8-4fab-9618-6f07f61cdd17)

![image](https://github.com/mawaqit/android-tv-app/assets/9025636/c77fe423-4f1d-4196-a86b-08a0dbf4f912)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
I tested the issue, please keep the language screen in the on boarding, just select the default language, don't remove the screen
