### ISSUE TITLE
Walkthrough is not running for ever in the developer home screen

### ISSUE THREAD

**Issue by Salahaldeen-altous** [mawaqit/android-tv-app#986]
Walk-Through is only running for 2 times and then stop.
this should run for ever or until you press number 6 to cancel the Walk-Through

it must be Walk-Through and not walk throw!!

Tested with version 1.8.2-276 on Onvo TV
![IMG-20240103-WA0027.jpeg](https://github.com/mawaqit/android-tv-app/assets/9025636/3fc95658-b7f3-40d2-99ce-0d378b60ac1b)

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Not working as expected
When the  Walk through finishes it stuck on announcements
