### ISSUE TITLE
Adhan and Iqamaa countdown not displayed

### ISSUE THREAD

**Issue by alias2006** [mawaqit/android-tv-app#988]
**Describe the bug**
When application is started after Adhan beginning time, neither Adhan nor Iqamaa countdown are displayed
only the normal screen is displayed.

**To Reproduce**
Start  the application after Adhan beginning time or during the Iqamaa countdown.

**Expected behavior**
If the Adhan duration time is not completed, the Adhan is displayed.
If the Adhan duration time is completed, the Iqamaa countdown is displayed. 

**Android TV/Box (please complete the following information):**
 - Device: Android TV
 - OS: [e.g. Android 10]
 - Version [e.g. 1.8.2]
- Build [e.g. 276]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Thanks brother
It's an edge case, so just restart the app and everything will be ok
