### ISSUE TITLE
Weather display temperature

### ISSUE THREAD

**Issue by alias2006** [mawaqit/android-tv-app#989]
**Describe the bug**
The °C in Arabic is displayed on the RIGHT of temperature value not on the left : 17°C and not °C17

**Expected behavior**
The °C in Arabic is displayed on the right of temperature.
We can keep the behavior of older version : Weather icon and temperature are displayed on the upper Right Corner.

**Android TV/Box :**
 - Device: [Androind TV]
 - OS: [Android 10]
 - Version [1.8.2]
- Build [276]

**Comment by ibrahim-zehhaf-mawaqit** [comment]
Salam alaykum brother 
Thank you for your reporting issue
We prefer keep the format in English
