### ISSUE TITLE
Add Location Next to Jumah Prayer

### ISSUE THREAD

**Issue by sohemokashi** [mawaqit/android-tv-app#992]
**Is your feature request related to a problem? Please describe.**

we have 2 location for Friday prayer , One is Mosque and other is Seperate hall . people get confused on prayer times and reach sometimes Mosque sometimes Hall 

**Describe the solution you'd like**

Can we add text box next to Jummah and if it's filled in configuration then show the Value of the box next to Clock Widget.

**Describe alternatives you've considered**

**Additional context**

**Comment by sohemokashi** [comment]
@mosman01 Please let me know if you need addition details or let me know if you want to implement this , Jazak Allah Khair

**Comment by msamiurr** [comment]
Assalamu Alaikum Brother, This is an urgent task, could you pls assign this to someone. Let me or Sohel know if you have any question.
JazakaAllah
Sami

**Comment by ibrahim-zehhaf-mawaqit** [comment]
It's a very specific request, it's an exception.
We can't adapt our system for all mosques specifications.
Sorry we can't do that.
You can inform the worshipers by a flash message
